<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Nationality;

class NationalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $nationalities = [
            ["gentile" => "afegãne", "country_name" => "Afeganistão", "int_country_name" => "Afghanistan", "abbreviation" => "AF"],
            ["gentile" => "sul-africana", "country_name" => "África do Sul", "int_country_name" => "South Africa", "abbreviation" => "ZA"],
            ["gentile" => "albanesa", "country_name" => "Albânia", "int_country_name" => "Albania", "abbreviation" => "AL"],
            ["gentile" => "alemã", "country_name" => "Alemanha", "int_country_name" => "Germany", "abbreviation" => "DE"],
            ["gentile" => "andorrana", "country_name" => "Andorra", "int_country_name" => "Andorra", "abbreviation" => "AD"],
            ["gentile" => "angolana", "country_name" => "Angola", "int_country_name" => "Angola", "abbreviation" => "AO"],
            ["gentile" => "anguillana", "country_name" => "Anguilla", "int_country_name" => "Anguilla", "abbreviation" => "AI"],
            ["gentile" => "de antártida", "country_name" => "Antártida", "int_country_name" => "Antarctica", "abbreviation" => "AQ"],
            ["gentile" => "antiguana", "country_name" => "Antígua e Barbuda", "int_country_name" => "Antigua & Barbuda", "abbreviation" => "AG"],
            ["gentile" => "saudita", "country_name" => "Arábia Saudita", "int_country_name" => "Saudi Arabia", "abbreviation" => "SA"],
            ["gentile" => "argelina", "country_name" => "Argélia", "int_country_name" => "Algeria", "abbreviation" => "DZ"],
            ["gentile" => "argentina", "country_name" => "Argentina", "int_country_name" => "Argentina", "abbreviation" => "AR"],
            ["gentile" => "armênia", "country_name" => "Armênia", "int_country_name" => "Armenia", "abbreviation" => "AM"],
            ["gentile" => "arubana", "country_name" => "Aruba", "int_country_name" => "Aruba", "abbreviation" => "AW"],
            ["gentile" => "australiana", "country_name" => "Austrália", "int_country_name" => "Australia", "abbreviation" => "AU"],
            ["gentile" => "austríaca", "country_name" => "Áustria", "int_country_name" => "Austria", "abbreviation" => "AT"],
            ["gentile" => "azerbaijano", "country_name" => "Azerbaijão", "int_country_name" => "Azerbaijan", "abbreviation" => "AZ"],
            ["gentile" => "bahamense", "country_name" => "Bahamas", "int_country_name" => "Bahamas", "abbreviation" => "BS"],
            ["gentile" => "barenita", "country_name" => "Bahrein", "int_country_name" => "Bahrain", "abbreviation" => "BH"],
            ["gentile" => "bengali", "country_name" => "Bangladesh", "int_country_name" => "Bangladesh", "abbreviation" => "BD"],
            ["gentile" => "barbadiana", "country_name" => "Barbados", "int_country_name" => "Barbados", "abbreviation" => "BB"],
            ["gentile" => "bielo-russa", "country_name" => "Belarus", "int_country_name" => "Belarus", "abbreviation" => "BY"],
            ["gentile" => "belga", "country_name" => "Bélgica", "int_country_name" => "Belgium", "abbreviation" => "BE"],
            ["gentile" => "belizenha", "country_name" => "Belize", "int_country_name" => "Belize", "abbreviation" => "BZ"],
            ["gentile" => "beninense", "country_name" => "Benin", "int_country_name" => "Benin", "abbreviation" => "BJ"],
            ["gentile" => "bermudiana", "country_name" => "Bermudas", "int_country_name" => "Bermuda", "abbreviation" => "BM"],
            ["gentile" => "boliviana", "country_name" => "Bolívia", "int_country_name" => "Bolivia", "abbreviation" => "BO"],
            ["gentile" => "bósnia", "country_name" => "Bósnia-Herzegóvina", "int_country_name" => "Bosnia & Herzegovina", "abbreviation" => "BA"],
            ["gentile" => "betchuana", "country_name" => "Botsuana", "int_country_name" => "Botswana", "abbreviation" => "BW"],
            ["gentile" => "brasileira", "country_name" => "Brasil", "int_country_name" => "Brazil", "abbreviation" => "BR"],
            ["gentile" => "bruneiana", "country_name" => "Brunei", "int_country_name" => "Brunei", "abbreviation" => "BN"],
            ["gentile" => "búlgara", "country_name" => "Bulgária", "int_country_name" => "Bulgaria", "abbreviation" => "BG"],
            ["gentile" => "burquinês", "country_name" => "Burkina Fasso", "int_country_name" => "Burkina Faso", "abbreviation" => "BF"],
            ["gentile" => "burundinesa", "country_name" => "Burundi", "int_country_name" => "Burundi", "abbreviation" => "BI"],
            ["gentile" => "butanesa", "country_name" => "Butão", "int_country_name" => "Bhutan", "abbreviation" => "BT"],
            ["gentile" => "cabo-verdiana", "country_name" => "Cabo Verde", "int_country_name" => "Cape Verde", "abbreviation" => "CV"],
            ["gentile" => "camaronesa", "country_name" => "Camarões", "int_country_name" => "Cameroon", "abbreviation" => "CM"],
            ["gentile" => "cambojana", "country_name" => "Camboja", "int_country_name" => "Cambodia", "abbreviation" => "KH"],
            ["gentile" => "canadense", "country_name" => "Canadá", "int_country_name" => "Canada", "abbreviation" => "CA"],
            ["gentile" => "canário", "country_name" => "Canárias", "int_country_name" => "Canary Islands", "abbreviation" => "IC"],
            ["gentile" => "cazaque", "country_name" => "Cazaquistão", "int_country_name" => "Kazakhstan", "abbreviation" => "KZ"],
            ["gentile" => "de ceuta e melilla", "country_name" => "Ceuta e Melilla", "int_country_name" => "Ceuta & Melilla", "abbreviation" => "EA"],
            ["gentile" => "chadiana", "country_name" => "Chade", "int_country_name" => "Chad", "abbreviation" => "TD"],
            ["gentile" => "chilena", "country_name" => "Chile", "int_country_name" => "Chile", "abbreviation" => "CL"],
            ["gentile" => "chinesa", "country_name" => "China", "int_country_name" => "China", "abbreviation" => "CN"],
            ["gentile" => "cipriota", "country_name" => "Chipre", "int_country_name" => "Cyprus", "abbreviation" => "CY"],
            ["gentile" => "cingapuriana", "country_name" => "Cingapura", "int_country_name" => "Singapore", "abbreviation" => "SG"],
            ["gentile" => "colombiana", "country_name" => "Colômbia", "int_country_name" => "Colombia", "abbreviation" => "CO"],
            ["gentile" => "comorense", "country_name" => "Comores", "int_country_name" => "Comoros", "abbreviation" => "KM"],
            ["gentile" => "congolesa", "country_name" => "Congo", "int_country_name" => "Congo (Republic)", "abbreviation" => "CG"],
            ["gentile" => "norte-coreano", "country_name" => "Coréia do Norte", "int_country_name" => "North Korea", "abbreviation" => "KP"],
            ["gentile" => "norte-coreana", "country_name" => "Coréia do Sul", "int_country_name" => "South Korea", "abbreviation" => "KR"],
            ["gentile" => "marfinense", "country_name" => "Costa do Marfim", "int_country_name" => "Côte d¿Ivoire", "abbreviation" => "CI"],
            ["gentile" => "costarriquenha", "country_name" => "Costa Rica", "int_country_name" => "Costa Rica", "abbreviation" => "CR"],
            ["gentile" => "croata", "country_name" => "Croácia", "int_country_name" => "Croatia", "abbreviation" => "HR"],
            ["gentile" => "cubana", "country_name" => "Cuba", "int_country_name" => "Cuba", "abbreviation" => "CU"],
            ["gentile" => "curaçauense", "country_name" => "Curaçao", "int_country_name" => "Curaçao", "abbreviation" => "CW"],
            ["gentile" => "chagositano", "country_name" => "Diego Garcia", "int_country_name" => "Diego Garcia", "abbreviation" => "DG"],
            ["gentile" => "dinamarquesa", "country_name" => "Dinamarca", "int_country_name" => "Denmark", "abbreviation" => "DK"],
            ["gentile" => "djibutiana", "country_name" => "Djibuti", "int_country_name" => "Djibouti", "abbreviation" => "DJ"],
            ["gentile" => "dominiquense", "country_name" => "Dominica", "int_country_name" => "Dominica", "abbreviation" => "DM"],
            ["gentile" => "egípcia", "country_name" => "Egito", "int_country_name" => "Egypt", "abbreviation" => "EG"],
            ["gentile" => "salvadorenha", "country_name" => "El Salvador", "int_country_name" => "El Salvador", "abbreviation" => "SV"],
            ["gentile" => "árabe", "country_name" => "Emirados Árabes Unidos", "int_country_name" => "United Arab Emirates", "abbreviation" => "AE"],
            ["gentile" => "equatoriana", "country_name" => "Equador", "int_country_name" => "Ecuador", "abbreviation" => "EC"],
            ["gentile" => "eritreia", "country_name" => "Eritréia", "int_country_name" => "Eritrea", "abbreviation" => "ER"],
            ["gentile" => "eslovaco", "country_name" => "Eslováquia", "int_country_name" => "Slovakia", "abbreviation" => "SK"],
            ["gentile" => "esloveno", "country_name" => "Eslovênia", "int_country_name" => "Slovenia", "abbreviation" => "SI"],
            ["gentile" => "espanhola", "country_name" => "Espanha", "int_country_name" => "Spain", "abbreviation" => "ES"],
            ["gentile" => "norte-americana", "country_name" => "Estados Unidos", "int_country_name" => "United States", "abbreviation" => "US"],
            ["gentile" => "estoniana", "country_name" => "Estônia", "int_country_name" => "Estonia", "abbreviation" => "EE"],
            ["gentile" => "etíope", "country_name" => "Etiópia", "int_country_name" => "Ethiopia", "abbreviation" => "ET"],
            ["gentile" => "fijiana", "country_name" => "Fiji", "int_country_name" => "Fiji", "abbreviation" => "FJ"],
            ["gentile" => "filipina", "country_name" => "Filipinas", "int_country_name" => "Philippines", "abbreviation" => "PH"],
            ["gentile" => "finlandesa", "country_name" => "Finlândia", "int_country_name" => "Finland", "abbreviation" => "FI"],
            ["gentile" => "francesa", "country_name" => "França", "int_country_name" => "France", "abbreviation" => "FR"],
            ["gentile" => "gabonesa", "country_name" => "Gabão", "int_country_name" => "Gabon", "abbreviation" => "GA"],
            ["gentile" => "gambiana", "country_name" => "Gâmbia", "int_country_name" => "Gambia", "abbreviation" => "GM"],
            ["gentile" => "ganense", "country_name" => "Gana", "int_country_name" => "Ghana", "abbreviation" => "GH"],
            ["gentile" => "georgiana", "country_name" => "Geórgia", "int_country_name" => "Georgia", "abbreviation" => "GE"],
            ["gentile" => "gibraltariana", "country_name" => "Gibraltar", "int_country_name" => "Gibraltar", "abbreviation" => "GI"],
            ["gentile" => "inglesa", "country_name" => "Grã-Bretanha (Reino Unido, UK)", "int_country_name" => "United Kingdom", "abbreviation" => "GB"],
            ["gentile" => "granadina", "country_name" => "Granada", "int_country_name" => "Grenada", "abbreviation" => "GD"],
            ["gentile" => "grega", "country_name" => "Grécia", "int_country_name" => "Greece", "abbreviation" => "GR"],
            ["gentile" => "groenlandesa", "country_name" => "Groelândia", "int_country_name" => "Greenland", "abbreviation" => "GL"],
            ["gentile" => "guadalupense", "country_name" => "Guadalupe", "int_country_name" => "Guadeloupe", "abbreviation" => "GP"],
            ["gentile" => "guamês", "country_name" => "Guam (Território dos Estados Unidos)", "int_country_name" => "Guam", "abbreviation" => "GU"],
            ["gentile" => "guatemalteca", "country_name" => "Guatemala", "int_country_name" => "Guatemala", "abbreviation" => "GT"],
            ["gentile" => "guernesiano", "country_name" => "Guernsey", "int_country_name" => "Guernsey", "abbreviation" => "GG"],
            ["gentile" => "guianense", "country_name" => "Guiana", "int_country_name" => "Guyana", "abbreviation" => "GY"],
            ["gentile" => "franco-guianense", "country_name" => "Guiana Francesa", "int_country_name" => "French Guiana", "abbreviation" => "GF"],
            ["gentile" => "guinéu-equatoriano ou equatoguineana", "country_name" => "Guiné", "int_country_name" => "Guinea", "abbreviation" => "GN"],
            ["gentile" => "guinéu-equatoriano", "country_name" => "Guiné Equatorial", "int_country_name" => "Equatorial Guinea", "abbreviation" => "GQ"],
            ["gentile" => "guineense", "country_name" => "Guiné-Bissau", "int_country_name" => "Guinea-Bissau", "abbreviation" => "GW"],
            ["gentile" => "haitiana", "country_name" => "Haiti", "int_country_name" => "Haiti", "abbreviation" => "HT"],
            ["gentile" => "holandês", "country_name" => "Holanda", "int_country_name" => "Netherlands", "abbreviation" => "NL"],
            ["gentile" => "hondurenha", "country_name" => "Honduras", "int_country_name" => "Honduras", "abbreviation" => "HN"],
            ["gentile" => "hong-konguiana ou chinesa", "country_name" => "Hong Kong", "int_country_name" => "Hong Kong", "abbreviation" => "HK"],
            ["gentile" => "húngara", "country_name" => "Hungria", "int_country_name" => "Hungary", "abbreviation" => "HU"],
            ["gentile" => "iemenita", "country_name" => "Iêmen", "int_country_name" => "Yemen", "abbreviation" => "YE"],
            ["gentile" => "da ilha bouvet", "country_name" => "Ilha Bouvet", "int_country_name" => "Bouvet Island", "abbreviation" => "BV"],
            ["gentile" => "da ilha de ascensão", "country_name" => "Ilha de Ascensão", "int_country_name" => "Ascension Island", "abbreviation" => "AC"],
            ["gentile" => "da ilha de clipperton", "country_name" => "Ilha de Clipperton", "int_country_name" => "Clipperton Island", "abbreviation" => "CP"],
            ["gentile" => "manês", "country_name" => "Ilha de Man", "int_country_name" => "Isle of Man", "abbreviation" => "IM"],
            ["gentile" => "natalense", "country_name" => "Ilha Natal", "int_country_name" => "Christmas Island", "abbreviation" => "CX"],
            ["gentile" => "pitcairnense", "country_name" => "Ilha Pitcairn", "int_country_name" => "Pitcairn Islands", "abbreviation" => "PN"],
            ["gentile" => "reunionense", "country_name" => "Ilha Reunião", "int_country_name" => "Réunion", "abbreviation" => "RE"],
            ["gentile" => "alandês", "country_name" => "Ilhas Aland", "int_country_name" => "Åland Islands", "abbreviation" => "AX"],
            ["gentile" => "caimanês", "country_name" => "Ilhas Cayman", "int_country_name" => "Cayman Islands", "abbreviation" => "KY"],
            ["gentile" => "coquense", "country_name" => "Ilhas Cocos", "int_country_name" => "Cocos (Keeling) Islands", "abbreviation" => "CC"],
            ["gentile" => "cookense", "country_name" => "Ilhas Cook", "int_country_name" => "Cook Islands", "abbreviation" => "CK"],
            ["gentile" => "faroense", "country_name" => "Ilhas Faroes", "int_country_name" => "Faroe Islands", "abbreviation" => "FO"],
            ["gentile" => "das ilhas geórgia do sul e sandwich do sul", "country_name" => "Ilhas Geórgia do Sul e Sandwich do Sul", "int_country_name" => "South Georgia & South Sandwich Islands", "abbreviation" => "GS"],
            ["gentile" => "das ilhas heard e mcdonald", "country_name" => "Ilhas Heard e McDonald (Território da Austrália)", "int_country_name" => "Heard & McDonald Islands", "abbreviation" => "HM"],
            ["gentile" => "malvinense", "country_name" => "Ilhas Malvinas", "int_country_name" => "Falkland Islands (Islas Malvinas)", "abbreviation" => "FK"],
            ["gentile" => "norte-marianense", "country_name" => "Ilhas Marianas do Norte", "int_country_name" => "Northern Mariana Islands", "abbreviation" => "MP"],
            ["gentile" => "marshallino", "country_name" => "Ilhas Marshall", "int_country_name" => "Marshall Islands", "abbreviation" => "MH"],
            ["gentile" => "das ilhas menores afastadas", "country_name" => "Ilhas Menores dos Estados Unidos", "int_country_name" => "U.S. Outlying Islands", "abbreviation" => "UM"],
            ["gentile" => "norfolquino", "country_name" => "Ilhas Norfolk", "int_country_name" => "Norfolk Island", "abbreviation" => "NF"],
            ["gentile" => "salomônico", "country_name" => "Ilhas Salomão", "int_country_name" => "Solomon Islands", "abbreviation" => "SB"],
            ["gentile" => "seichelense", "country_name" => "Ilhas Seychelles", "int_country_name" => "Seychelles", "abbreviation" => "SC"],
            ["gentile" => "toquelauano", "country_name" => "Ilhas Tokelau", "int_country_name" => "Tokelau", "abbreviation" => "TK"],
            ["gentile" => "turquês", "country_name" => "Ilhas Turks e Caicos", "int_country_name" => "Turks & Caicos Islands", "abbreviation" => "TC"],
            ["gentile" => "virginense", "country_name" => "Ilhas Virgens (Estados Unidos)", "int_country_name" => "U.S. Virgin Islands", "abbreviation" => "VI"],
            ["gentile" => "virginense", "country_name" => "Ilhas Virgens (Inglaterra)", "int_country_name" => "British Virgin Islands", "abbreviation" => "VG"],
            ["gentile" => "indiano", "country_name" => "Índia", "int_country_name" => "India", "abbreviation" => "IN"],
            ["gentile" => "indonésia", "country_name" => "Indonésia", "int_country_name" => "Indonesia", "abbreviation" => "ID"],
            ["gentile" => "iraniano", "country_name" => "Irã", "int_country_name" => "Iran", "abbreviation" => "IR"],
            ["gentile" => "iraquiana", "country_name" => "Iraque", "int_country_name" => "Iraq", "abbreviation" => "IQ"],
            ["gentile" => "irlandesa", "country_name" => "Irlanda", "int_country_name" => "Ireland", "abbreviation" => "IE"],
            ["gentile" => "islandesa", "country_name" => "Islândia", "int_country_name" => "Iceland", "abbreviation" => "IS"],
            ["gentile" => "israelense", "country_name" => "Israel", "int_country_name" => "Israel", "abbreviation" => "IL"],
            ["gentile" => "italiana", "country_name" => "Itália", "int_country_name" => "Italy", "abbreviation" => "IT"],
            ["gentile" => "jamaicana", "country_name" => "Jamaica", "int_country_name" => "Jamaica", "abbreviation" => "JM"],
            ["gentile" => "japonesa", "country_name" => "Japão", "int_country_name" => "Japan", "abbreviation" => "JP"],
            ["gentile" => "canalina", "country_name" => "Jersey", "int_country_name" => "Jersey", "abbreviation" => "JE"],
            ["gentile" => "jordaniana", "country_name" => "Jordânia", "int_country_name" => "Jordan", "abbreviation" => "JO"],
            ["gentile" => "kiribatiana", "country_name" => "Kiribati", "int_country_name" => "Kiribati", "abbreviation" => "KI"],
            ["gentile" => "kosovar", "country_name" => "Kosovo", "int_country_name" => "Kosovo", "abbreviation" => "XK"],
            ["gentile" => "kuwaitiano", "country_name" => "Kuait", "int_country_name" => "Kuwait", "abbreviation" => "KW"],
            ["gentile" => "laosiana", "country_name" => "Laos", "int_country_name" => "Laos", "abbreviation" => "LA"],
            ["gentile" => "lesota", "country_name" => "Lesoto", "int_country_name" => "Lesotho", "abbreviation" => "LS"],
            ["gentile" => "letão", "country_name" => "Letônia", "int_country_name" => "Latvia", "abbreviation" => "LV"],
            ["gentile" => "libanesa", "country_name" => "Líbano", "int_country_name" => "Lebanon", "abbreviation" => "LB"],
            ["gentile" => "liberiana", "country_name" => "Libéria", "int_country_name" => "Liberia", "abbreviation" => "LR"],
            ["gentile" => "líbia", "country_name" => "Líbia", "int_country_name" => "Libya", "abbreviation" => "LY"],
            ["gentile" => "liechtensteiniense", "country_name" => "Liechtenstein", "int_country_name" => "Liechtenstein", "abbreviation" => "LI"],
            ["gentile" => "lituana", "country_name" => "Lituânia", "int_country_name" => "Lithuania", "abbreviation" => "LT"],
            ["gentile" => "luxemburguesa", "country_name" => "Luxemburgo", "int_country_name" => "Luxembourg", "abbreviation" => "LU"],
            ["gentile" => "macauense", "country_name" => "Macau", "int_country_name" => "Macau", "abbreviation" => "MO"],
            ["gentile" => "macedônio", "country_name" => "Macedônia (República Yugoslava)", "int_country_name" => "Macedonia (FYROM)", "abbreviation" => "MK"],
            ["gentile" => "malgaxe", "country_name" => "Madagascar", "int_country_name" => "Madagascar", "abbreviation" => "MG"],
            ["gentile" => "malaia", "country_name" => "Malásia", "int_country_name" => "Malaysia", "abbreviation" => "MY"],
            ["gentile" => "malauiano", "country_name" => "Malaui", "int_country_name" => "Malawi", "abbreviation" => "MW"],
            ["gentile" => "maldívia", "country_name" => "Maldivas", "int_country_name" => "Maldives", "abbreviation" => "MV"],
            ["gentile" => "malinesa", "country_name" => "Mali", "int_country_name" => "Mali", "abbreviation" => "ML"],
            ["gentile" => "maltesa", "country_name" => "Malta", "int_country_name" => "Malta", "abbreviation" => "MT"],
            ["gentile" => "marroquina", "country_name" => "Marrocos", "int_country_name" => "Morocco", "abbreviation" => "MA"],
            ["gentile" => "martiniquense", "country_name" => "Martinica", "int_country_name" => "Martinique", "abbreviation" => "MQ"],
            ["gentile" => "mauriciana", "country_name" => "Maurício", "int_country_name" => "Mauritius", "abbreviation" => "MU"],
            ["gentile" => "mauritana", "country_name" => "Mauritânia", "int_country_name" => "Mauritania", "abbreviation" => "MR"],
            ["gentile" => "maiotense", "country_name" => "Mayotte", "int_country_name" => "Mayotte", "abbreviation" => "YT"],
            ["gentile" => "mexicana", "country_name" => "México", "int_country_name" => "Mexico", "abbreviation" => "MX"],
            ["gentile" => "micronésia", "country_name" => "Micronésia", "int_country_name" => "Micronesia", "abbreviation" => "FM"],
            ["gentile" => "moçambicana", "country_name" => "Moçambique", "int_country_name" => "Mozambique", "abbreviation" => "MZ"],
            ["gentile" => "moldavo", "country_name" => "Moldova", "int_country_name" => "Moldova", "abbreviation" => "MD"],
            ["gentile" => "monegasca", "country_name" => "Mônaco", "int_country_name" => "Monaco", "abbreviation" => "MC"],
            ["gentile" => "mongol", "country_name" => "Mongólia", "int_country_name" => "Mongolia", "abbreviation" => "MN"],
            ["gentile" => "montenegra", "country_name" => "Montenegro", "int_country_name" => "Montenegro", "abbreviation" => "ME"],
            ["gentile" => "montserratiano", "country_name" => "Montserrat", "int_country_name" => "Montserrat", "abbreviation" => "MS"],
            ["gentile" => "birmanês", "country_name" => "Myanma", "int_country_name" => "Myanmar (Burma)", "abbreviation" => "MM"],
            ["gentile" => "namíbia", "country_name" => "Namíbia", "int_country_name" => "Namibia", "abbreviation" => "NA"],
            ["gentile" => "nauruana", "country_name" => "Nauru", "int_country_name" => "Nauru", "abbreviation" => "NR"],
            ["gentile" => "nepalesa", "country_name" => "Nepal", "int_country_name" => "Nepal", "abbreviation" => "NP"],
            ["gentile" => "nicaraguense", "country_name" => "Nicarágua", "int_country_name" => "Nicaragua", "abbreviation" => "NI"],
            ["gentile" => "nigerina", "country_name" => "Níger", "int_country_name" => "Niger", "abbreviation" => "NE"],
            ["gentile" => "nigeriana", "country_name" => "Nigéria", "int_country_name" => "Nigeria", "abbreviation" => "NG"],
            ["gentile" => "niueana", "country_name" => "Niue", "int_country_name" => "Niue", "abbreviation" => "NU"],
            ["gentile" => "norueguesa", "country_name" => "Noruega", "int_country_name" => "Norway", "abbreviation" => "NO"],
            ["gentile" => "caledônia", "country_name" => "Nova Caledônia", "int_country_name" => "New Caledonia", "abbreviation" => "NC"],
            ["gentile" => "neozelandesa", "country_name" => "Nova Zelândia", "int_country_name" => "New Zealand", "abbreviation" => "NZ"],
            ["gentile" => "omani", "country_name" => "Omã", "int_country_name" => "Oman", "abbreviation" => "OM"],
            ["gentile" => "dos países baixos caribenhos", "country_name" => "Países Baixos Caribenhos", "int_country_name" => "Caribbean Netherlands", "abbreviation" => "BQ"],
            ["gentile" => "palauense", "country_name" => "Palau", "int_country_name" => "Palau", "abbreviation" => "PW"],
            ["gentile" => "palestino", "country_name" => "Palestina", "int_country_name" => "Palestine", "abbreviation" => "PS"],
            ["gentile" => "zona do canal do panamá", "country_name" => "Panamá", "int_country_name" => "Panama", "abbreviation" => "PA"],
            ["gentile" => "pauásia", "country_name" => "Papua-Nova Guiné", "int_country_name" => "Papua New Guinea", "abbreviation" => "PG"],
            ["gentile" => "paquistanesa", "country_name" => "Paquistão", "int_country_name" => "Pakistan", "abbreviation" => "PK"],
            ["gentile" => "paraguaia", "country_name" => "Paraguai", "int_country_name" => "Paraguay", "abbreviation" => "PY"],
            ["gentile" => "peruana", "country_name" => "Peru", "int_country_name" => "Peru", "abbreviation" => "PE"],
            ["gentile" => "franco-polinésia", "country_name" => "Polinésia Francesa", "int_country_name" => "French Polynesia", "abbreviation" => "PF"],
            ["gentile" => "polonesa", "country_name" => "Polônia", "int_country_name" => "Poland", "abbreviation" => "PL"],
            ["gentile" => "portorriquenha", "country_name" => "Porto Rico", "int_country_name" => "Puerto Rico", "abbreviation" => "PR"],
            ["gentile" => "portuguesa", "country_name" => "Portugal", "int_country_name" => "Portugal", "abbreviation" => "PT"],
            ["gentile" => "catarense", "country_name" => "Qatar", "int_country_name" => "Qatar", "abbreviation" => "QA"],
            ["gentile" => "queniano", "country_name" => "Quênia", "int_country_name" => "Kenya", "abbreviation" => "KE"],
            ["gentile" => "quirguiz", "country_name" => "Quirguistão", "int_country_name" => "Kyrgyzstan", "abbreviation" => "KG"],
            ["gentile" => "centro-africana", "country_name" => "República Centro-Africana", "int_country_name" => "Central African Republic", "abbreviation" => "CF"],
            ["gentile" => "congolesa", "country_name" => "República Democrática do Congo", "int_country_name" => "Congo (DRC)", "abbreviation" => "CD"],
            ["gentile" => "dominicana", "country_name" => "República Dominicana", "int_country_name" => "Dominican Republic", "abbreviation" => "DO"],
            ["gentile" => "tcheco", "country_name" => "República Tcheca", "int_country_name" => "Czech Republic", "abbreviation" => "CZ"],
            ["gentile" => "romena", "country_name" => "Romênia", "int_country_name" => "Romania", "abbreviation" => "RO"],
            ["gentile" => "ruandesa", "country_name" => "Ruanda", "int_country_name" => "Rwanda", "abbreviation" => "RW"],
            ["gentile" => "russa", "country_name" => "Rússia (antiga URSS) - Federação Russa", "int_country_name" => "Russia", "abbreviation" => "RU"],
            ["gentile" => "saariano", "country_name" => "Saara Ocidental", "int_country_name" => "Western Sahara", "abbreviation" => "EH"],
            ["gentile" => "pedro-miquelonense", "country_name" => "Saint-Pierre e Miquelon", "int_country_name" => "St. Pierre & Miquelon", "abbreviation" => "PM"],
            ["gentile" => "samoana", "country_name" => "Samoa Americana", "int_country_name" => "American Samoa", "abbreviation" => "AS"],
            ["gentile" => "samoano", "country_name" => "Samoa Ocidental", "int_country_name" => "Samoa", "abbreviation" => "WS"],
            ["gentile" => "samarinês", "country_name" => "San Marino", "int_country_name" => "San Marino", "abbreviation" => "SM"],
            ["gentile" => "helenense", "country_name" => "Santa Helena", "int_country_name" => "St. Helena", "abbreviation" => "SH"],
            ["gentile" => "santa-lucense", "country_name" => "Santa Lúcia", "int_country_name" => "St. Lucia", "abbreviation" => "LC"],
            ["gentile" => "são-bartolomeense", "country_name" => "São Bartolomeu", "int_country_name" => "St. Barthélemy", "abbreviation" => "BL"],
            ["gentile" => "são-cristovense", "country_name" => "São Cristóvão e Névis", "int_country_name" => "St. Kitts & Nevis", "abbreviation" => "KN"],
            ["gentile" => "são-martinhense", "country_name" => "São Martim", "int_country_name" => "St. Martin", "abbreviation" => "MF"],
            ["gentile" => "são-martinhense", "country_name" => "São Martinho", "int_country_name" => "Sint Maarten", "abbreviation" => "SX"],
            ["gentile" => "são-tomense", "country_name" => "São Tomé e Príncipe", "int_country_name" => "São Tomé & Príncipe", "abbreviation" => "ST"],
            ["gentile" => "sao-vicentino", "country_name" => "São Vicente e Granadinas", "int_country_name" => "St. Vincent & Grenadines", "abbreviation" => "VC"],
            ["gentile" => "senegalesa", "country_name" => "Senegal", "int_country_name" => "Senegal", "abbreviation" => "SN"],
            ["gentile" => "leonesa", "country_name" => "Serra Leoa", "int_country_name" => "Sierra Leone", "abbreviation" => "SL"],
            ["gentile" => "sérvia", "country_name" => "Sérvia", "int_country_name" => "Serbia", "abbreviation" => "RS"],
            ["gentile" => "síria", "country_name" => "Síria", "int_country_name" => "Syria", "abbreviation" => "SY"],
            ["gentile" => "somali", "country_name" => "Somália", "int_country_name" => "Somalia", "abbreviation" => "SO"],
            ["gentile" => "cingalesa", "country_name" => "Sri Lanka", "int_country_name" => "Sri Lanka", "abbreviation" => "LK"],
            ["gentile" => "suazi", "country_name" => "Suazilândia", "int_country_name" => "Swaziland", "abbreviation" => "SZ"],
            ["gentile" => "sudanesa", "country_name" => "Sudão", "int_country_name" => "Sudan", "abbreviation" => "SD"],
            ["gentile" => "sul-sudanês", "country_name" => "Sudão do Sul", "int_country_name" => "South Sudan", "abbreviation" => "SS"],
            ["gentile" => "sueca", "country_name" => "Suécia", "int_country_name" => "Sweden", "abbreviation" => "SE"],
            ["gentile" => "suíça", "country_name" => "Suíça", "int_country_name" => "Switzerland", "abbreviation" => "CH"],
            ["gentile" => "surinamesa", "country_name" => "Suriname", "int_country_name" => "Suriname", "abbreviation" => "SR"],
            ["gentile" => "svalbardense", "country_name" => "Svalbard", "int_country_name" => "Svalbard & Jan Mayen", "abbreviation" => "SJ"],
            ["gentile" => "tadjique", "country_name" => "Tadjiquistão", "int_country_name" => "Tajikistan", "abbreviation" => "TJ"],
            ["gentile" => "tailandesa", "country_name" => "Tailândia", "int_country_name" => "Thailand", "abbreviation" => "TH"],
            ["gentile" => "taiwanês", "country_name" => "Taiwan", "int_country_name" => "Taiwan", "abbreviation" => "TW"],
            ["gentile" => "tanzaniana", "country_name" => "Tanzânia", "int_country_name" => "Tanzania", "abbreviation" => "TZ"],
            ["gentile" => "do território britânico do oceano índico", "country_name" => "Território Britânico do Oceano índico", "int_country_name" => "British Indian Ocean Territory", "abbreviation" => "IO"],
            ["gentile" => "do territórios do sul da frança", "country_name" => "Territórios do Sul da França", "int_country_name" => "French Southern Territories", "abbreviation" => "TF"],
            ["gentile" => "timorense", "country_name" => "Timor-Leste", "int_country_name" => "Timor-Leste", "abbreviation" => "TL"],
            ["gentile" => "togolesa", "country_name" => "Togo", "int_country_name" => "Togo", "abbreviation" => "TG"],
            ["gentile" => "tonganesa", "country_name" => "Tonga", "int_country_name" => "Tonga", "abbreviation" => "TO"],
            ["gentile" => "trinitário-tobagense", "country_name" => "Trinidad e Tobago", "int_country_name" => "Trinidad & Tobago", "abbreviation" => "TT"],
            ["gentile" => "tristanita", "country_name" => "Tristão da Cunha", "int_country_name" => "Tristan da Cunha", "abbreviation" => "TA"],
            ["gentile" => "tunisiana", "country_name" => "Tunísia", "int_country_name" => "Tunisia", "abbreviation" => "TN"],
            ["gentile" => "turcomana", "country_name" => "Turcomenistão", "int_country_name" => "Turkmenistan", "abbreviation" => "TM"],
            ["gentile" => "turca", "country_name" => "Turquia", "int_country_name" => "Turkey", "abbreviation" => "TR"],
            ["gentile" => "tuvaluana", "country_name" => "Tuvalu", "int_country_name" => "Tuvalu", "abbreviation" => "TV"],
            ["gentile" => "ucraniana", "country_name" => "Ucrânia", "int_country_name" => "Ukraine", "abbreviation" => "UA"],
            ["gentile" => "ugandense", "country_name" => "Uganda", "int_country_name" => "Uganda", "abbreviation" => "UG"],
            ["gentile" => "uruguaia", "country_name" => "Uruguai", "int_country_name" => "Uruguay", "abbreviation" => "UY"],
            ["gentile" => "uzbeque", "country_name" => "Uzbequistão", "int_country_name" => "Uzbekistan", "abbreviation" => "UZ"],
            ["gentile" => "vanuatuense", "country_name" => "Vanuatu", "int_country_name" => "Vanuatu", "abbreviation" => "VU"],
            ["gentile" => "vaticano", "country_name" => "Vaticano", "int_country_name" => "Vatican City", "abbreviation" => "VA"],
            ["gentile" => "venezuelana", "country_name" => "Venezuela", "int_country_name" => "Venezuela", "abbreviation" => "VE"],
            ["gentile" => "vietnamita", "country_name" => "Vietnã", "int_country_name" => "Vietnam", "abbreviation" => "VN"],
            ["gentile" => "wallis-futunense", "country_name" => "Wallis e Futuna", "int_country_name" => "Wallis & Futuna", "abbreviation" => "WF"],
            ["gentile" => "zambiana", "country_name" => "Zâmbia", "int_country_name" => "Zambia", "abbreviation" => "ZM"],
            ["gentile" => "zimbabuana", "country_name" => "Zimbábue", "int_country_name" => "Zimbabwe", "abbreviation" => "ZW"]
        ];

        if (empty(Nationality::all()->toArray())) {
            foreach ($nationalities as $nationality) {
                Nationality::create($nationality);
            }
        }
    }
}
