<option {{  $selected == 'fa fa-500px' ? 'selected' : '' }} value='fa fa-500px'>&#xf26e; 500px</option>
<option {{  $selected == 'fa fa-address-book' ? 'selected' : '' }} value='fa fa-address-book'>&#xf2b9; address-book</option>
<option {{  $selected == 'fa fa-address-book-o' ? 'selected' : '' }} value='fa fa-address-book-o'>&#xf2ba; address-book-o</option>
<option {{  $selected == 'fa fa-address-card' ? 'selected' : '' }} value='fa fa-address-card'>&#xf2bb; address-card</option>
<option {{  $selected == 'fa fa-address-card-o' ? 'selected' : '' }} value='fa fa-address-card-o'>&#xf2bc; address-card-o</option>
<option {{  $selected == 'fa fa-adjust' ? 'selected' : '' }} value='fa fa-adjust'>&#xf042; adjust</option>
<option {{  $selected == 'fa fa-adn' ? 'selected' : '' }} value='fa fa-adn'>&#xf170; adn</option>
<option {{  $selected == 'fa fa-align-center' ? 'selected' : '' }} value='fa fa-align-center'>&#xf037; align-center</option>
<option {{  $selected == 'fa fa-align-justify' ? 'selected' : '' }} value='fa fa-align-justify'>&#xf039; align-justify</option>
<option {{  $selected == 'fa fa-align-left' ? 'selected' : '' }} value='fa fa-align-left'>&#xf036; align-left</option>
<option {{  $selected == 'fa fa-align-right' ? 'selected' : '' }} value='fa fa-align-right'>&#xf038; align-right</option>
<option {{  $selected == 'fa fa-amazon' ? 'selected' : '' }} value='fa fa-amazon'>&#xf270; amazon</option>
<option {{  $selected == 'fa fa-ambulance' ? 'selected' : '' }} value='fa fa-ambulance'>&#xf0f9; ambulance</option>
<option {{  $selected == 'fa fa-american-sign-language-interpreting' ? 'selected' : '' }} value='fa fa-american-sign-language-interpreting'>&#xf2a3; american-sign-language-interpreting</option>
<option {{  $selected == 'fa fa-anchor' ? 'selected' : '' }} value='fa fa-anchor'>&#xf13d; anchor</option>
<option {{  $selected == 'fa fa-android' ? 'selected' : '' }} value='fa fa-android'>&#xf17b; android</option>
<option {{  $selected == 'fa fa-angellist' ? 'selected' : '' }} value='fa fa-angellist'>&#xf209; angellist</option>
<option {{  $selected == 'fa fa-angle-double-down' ? 'selected' : '' }} value='fa fa-angle-double-down'>&#xf103; angle-double-down</option>
<option {{  $selected == 'fa fa-angle-double-left' ? 'selected' : '' }} value='fa fa-angle-double-left'>&#xf100; angle-double-left</option>
<option {{  $selected == 'fa fa-angle-double-right' ? 'selected' : '' }} value='fa fa-angle-double-right'>&#xf101; angle-double-right</option>
<option {{  $selected == 'fa fa-angle-double-up' ? 'selected' : '' }} value='fa fa-angle-double-up'>&#xf102; angle-double-up</option>
<option {{  $selected == 'fa fa-angle-down' ? 'selected' : '' }} value='fa fa-angle-down'>&#xf107; angle-down</option>
<option {{  $selected == 'fa fa-angle-left' ? 'selected' : '' }} value='fa fa-angle-left'>&#xf104; angle-left</option>
<option {{  $selected == 'fa fa-angle-right' ? 'selected' : '' }} value='fa fa-angle-right'>&#xf105; angle-right</option>
<option {{  $selected == 'fa fa-angle-up' ? 'selected' : '' }} value='fa fa-angle-up'>&#xf106; angle-up</option>
<option {{  $selected == 'fa fa-apple' ? 'selected' : '' }} value='fa fa-apple'>&#xf179; apple</option>
<option {{  $selected == 'fa fa-archive' ? 'selected' : '' }} value='fa fa-archive'>&#xf187; archive</option>
<option {{  $selected == 'fa fa-area-chart' ? 'selected' : '' }} value='fa fa-area-chart'>&#xf1fe; area-chart</option>
<option {{  $selected == 'fa fa-arrow-circle-down' ? 'selected' : '' }} value='fa fa-arrow-circle-down'>&#xf0ab; arrow-circle-down</option>
<option {{  $selected == 'fa fa-arrow-circle-left' ? 'selected' : '' }} value='fa fa-arrow-circle-left'>&#xf0a8; arrow-circle-left</option>
<option {{  $selected == 'fa fa-arrow-circle-o-down' ? 'selected' : '' }} value='fa fa-arrow-circle-o-down'>&#xf01a; arrow-circle-o-down</option>
<option {{  $selected == 'fa fa-arrow-circle-o-left' ? 'selected' : '' }} value='fa fa-arrow-circle-o-left'>&#xf190; arrow-circle-o-left</option>
<option {{  $selected == 'fa fa-arrow-circle-o-right' ? 'selected' : '' }} value='fa fa-arrow-circle-o-right'>&#xf18e; arrow-circle-o-right</option>
<option {{  $selected == 'fa fa-arrow-circle-o-up' ? 'selected' : '' }} value='fa fa-arrow-circle-o-up'>&#xf01b; arrow-circle-o-up</option>
<option {{  $selected == 'fa fa-arrow-circle-right' ? 'selected' : '' }} value='fa fa-arrow-circle-right'>&#xf0a9; arrow-circle-right</option>
<option {{  $selected == 'fa fa-arrow-circle-up' ? 'selected' : '' }} value='fa fa-arrow-circle-up'>&#xf0aa; arrow-circle-up</option>
<option {{  $selected == 'fa fa-arrow-down' ? 'selected' : '' }} value='fa fa-arrow-down'>&#xf063; arrow-down</option>
<option {{  $selected == 'fa fa-arrow-left' ? 'selected' : '' }} value='fa fa-arrow-left'>&#xf060; arrow-left</option>
<option {{  $selected == 'fa fa-arrow-right' ? 'selected' : '' }} value='fa fa-arrow-right'>&#xf061; arrow-right</option>
<option {{  $selected == 'fa fa-arrow-up' ? 'selected' : '' }} value='fa fa-arrow-up'>&#xf062; arrow-up</option>
<option {{  $selected == 'fa fa-arrows' ? 'selected' : '' }} value='fa fa-arrows'>&#xf047; arrows</option>
<option {{  $selected == 'fa fa-arrows-alt' ? 'selected' : '' }} value='fa fa-arrows-alt'>&#xf0b2; arrows-alt</option>
<option {{  $selected == 'fa fa-arrows-h' ? 'selected' : '' }} value='fa fa-arrows-h'>&#xf07e; arrows-h</option>
<option {{  $selected == 'fa fa-arrows-v' ? 'selected' : '' }} value='fa fa-arrows-v'>&#xf07d; arrows-v</option>
<option {{  $selected == 'fa fa-asl-interpreting' ? 'selected' : '' }} value='fa fa-asl-interpreting'>&#xf2a3; asl-interpreting</option>
<option {{  $selected == 'fa fa-assistive-listening-systems' ? 'selected' : '' }} value='fa fa-assistive-listening-systems'>&#xf2a2; assistive-listening-systems</option>
<option {{  $selected == 'fa fa-asterisk' ? 'selected' : '' }} value='fa fa-asterisk'>&#xf069; asterisk</option>
<option {{  $selected == 'fa fa-at' ? 'selected' : '' }} value='fa fa-at'>&#xf1fa; at</option>
<option {{  $selected == 'fa fa-audio-description' ? 'selected' : '' }} value='fa fa-audio-description'>&#xf29e; audio-description</option>
<option {{  $selected == 'fa fa-automobile' ? 'selected' : '' }} value='fa fa-automobile'>&#xf1b9; automobile</option>
<option {{  $selected == 'fa fa-backward' ? 'selected' : '' }} value='fa fa-backward'>&#xf04a; backward</option>
<option {{  $selected == 'fa fa-balance-scale' ? 'selected' : '' }} value='fa fa-balance-scale'>&#xf24e; balance-scale</option>
<option {{  $selected == 'fa fa-ban' ? 'selected' : '' }} value='fa fa-ban'>&#xf05e; ban</option>
<option {{  $selected == 'fa fa-bandcamp' ? 'selected' : '' }} value='fa fa-bandcamp'>&#xf2d5; bandcamp</option>
<option {{  $selected == 'fa fa-bank' ? 'selected' : '' }} value='fa fa-bank'>&#xf19c; bank</option>
<option {{  $selected == 'fa fa-bar-chart' ? 'selected' : '' }} value='fa fa-bar-chart'>&#xf080; bar-chart</option>
<option {{  $selected == 'fa fa-bar-chart-o' ? 'selected' : '' }} value='fa fa-bar-chart-o'>&#xf080; bar-chart-o</option>
<option {{  $selected == 'fa fa-barcode' ? 'selected' : '' }} value='fa fa-barcode'>&#xf02a; barcode</option>
<option {{  $selected == 'fa fa-bars' ? 'selected' : '' }} value='fa fa-bars'>&#xf0c9; bars</option>
<option {{  $selected == 'fa fa-bath' ? 'selected' : '' }} value='fa fa-bath'>&#xf2cd; bath</option>
<option {{  $selected == 'fa fa-bathtub' ? 'selected' : '' }} value='fa fa-bathtub'>&#xf2cd; bathtub</option>
<option {{  $selected == 'fa fa-battery' ? 'selected' : '' }} value='fa fa-battery'>&#xf240; battery</option>
<option {{  $selected == 'fa fa-battery-0' ? 'selected' : '' }} value='fa fa-battery-0'>&#xf244; battery-0</option>
<option {{  $selected == 'fa fa-battery-1' ? 'selected' : '' }} value='fa fa-battery-1'>&#xf243; battery-1</option>
<option {{  $selected == 'fa fa-battery-2' ? 'selected' : '' }} value='fa fa-battery-2'>&#xf242; battery-2</option>
<option {{  $selected == 'fa fa-battery-3' ? 'selected' : '' }} value='fa fa-battery-3'>&#xf241; battery-3</option>
<option {{  $selected == 'fa fa-battery-4' ? 'selected' : '' }} value='fa fa-battery-4'>&#xf240; battery-4</option>
<option {{  $selected == 'fa fa-battery-empty' ? 'selected' : '' }} value='fa fa-battery-empty'>&#xf244; battery-empty</option>
<option {{  $selected == 'fa fa-battery-full' ? 'selected' : '' }} value='fa fa-battery-full'>&#xf240; battery-full</option>
<option {{  $selected == 'fa fa-battery-half' ? 'selected' : '' }} value='fa fa-battery-half'>&#xf242; battery-half</option>
<option {{  $selected == 'fa fa-battery-quarter' ? 'selected' : '' }} value='fa fa-battery-quarter'>&#xf243; battery-quarter</option>
<option {{  $selected == 'fa fa-battery-three-quarters' ? 'selected' : '' }} value='fa fa-battery-three-quarters'>&#xf241; battery-three-quarters</option>
<option {{  $selected == 'fa fa-bed' ? 'selected' : '' }} value='fa fa-bed'>&#xf236; bed</option>
<option {{  $selected == 'fa fa-beer' ? 'selected' : '' }} value='fa fa-beer'>&#xf0fc; beer</option>
<option {{  $selected == 'fa fa-behance' ? 'selected' : '' }} value='fa fa-behance'>&#xf1b4; behance</option>
<option {{  $selected == 'fa fa-behance-square' ? 'selected' : '' }} value='fa fa-behance-square'>&#xf1b5; behance-square</option>
<option {{  $selected == 'fa fa-bell' ? 'selected' : '' }} value='fa fa-bell'>&#xf0f3; bell</option>
<option {{  $selected == 'fa fa-bell-o' ? 'selected' : '' }} value='fa fa-bell-o'>&#xf0a2; bell-o</option>
<option {{  $selected == 'fa fa-bell-slash' ? 'selected' : '' }} value='fa fa-bell-slash'>&#xf1f6; bell-slash</option>
<option {{  $selected == 'fa fa-bell-slash-o' ? 'selected' : '' }} value='fa fa-bell-slash-o'>&#xf1f7; bell-slash-o</option>
<option {{  $selected == 'fa fa-bicycle' ? 'selected' : '' }} value='fa fa-bicycle'>&#xf206; bicycle</option>
<option {{  $selected == 'fa fa-binoculars' ? 'selected' : '' }} value='fa fa-binoculars'>&#xf1e5; binoculars</option>
<option {{  $selected == 'fa fa-birthday-cake' ? 'selected' : '' }} value='fa fa-birthday-cake'>&#xf1fd; birthday-cake</option>
<option {{  $selected == 'fa fa-bitbucket' ? 'selected' : '' }} value='fa fa-bitbucket'>&#xf171; bitbucket</option>
<option {{  $selected == 'fa fa-bitbucket-square' ? 'selected' : '' }} value='fa fa-bitbucket-square'>&#xf172; bitbucket-square</option>
<option {{  $selected == 'fa fa-bitcoin' ? 'selected' : '' }} value='fa fa-bitcoin'>&#xf15a; bitcoin</option>
<option {{  $selected == 'fa fa-black-tie' ? 'selected' : '' }} value='fa fa-black-tie'>&#xf27e; black-tie</option>
<option {{  $selected == 'fa fa-blind' ? 'selected' : '' }} value='fa fa-blind'>&#xf29d; blind</option>
<option {{  $selected == 'fa fa-bluetooth' ? 'selected' : '' }} value='fa fa-bluetooth'>&#xf293; bluetooth</option>
<option {{  $selected == 'fa fa-bluetooth-b' ? 'selected' : '' }} value='fa fa-bluetooth-b'>&#xf294; bluetooth-b</option>
<option {{  $selected == 'fa fa-bold' ? 'selected' : '' }} value='fa fa-bold'>&#xf032; bold</option>
<option {{  $selected == 'fa fa-bolt' ? 'selected' : '' }} value='fa fa-bolt'>&#xf0e7; bolt</option>
<option {{  $selected == 'fa fa-bomb' ? 'selected' : '' }} value='fa fa-bomb'>&#xf1e2; bomb</option>
<option {{  $selected == 'fa fa-book' ? 'selected' : '' }} value='fa fa-book'>&#xf02d; book</option>
<option {{  $selected == 'fa fa-bookmark' ? 'selected' : '' }} value='fa fa-bookmark'>&#xf02e; bookmark</option>
<option {{  $selected == 'fa fa-bookmark-o' ? 'selected' : '' }} value='fa fa-bookmark-o'>&#xf097; bookmark-o</option>
<option {{  $selected == 'fa fa-braille' ? 'selected' : '' }} value='fa fa-braille'>&#xf2a1; braille</option>
<option {{  $selected == 'fa fa-briefcase' ? 'selected' : '' }} value='fa fa-briefcase'>&#xf0b1; briefcase</option>
<option {{  $selected == 'fa fa-btc' ? 'selected' : '' }} value='fa fa-btc'>&#xf15a; btc</option>
<option {{  $selected == 'fa fa-bug' ? 'selected' : '' }} value='fa fa-bug'>&#xf188; bug</option>
<option {{  $selected == 'fa fa-building' ? 'selected' : '' }} value='fa fa-building'>&#xf1ad; building</option>
<option {{  $selected == 'fa fa-building-o' ? 'selected' : '' }} value='fa fa-building-o'>&#xf0f7; building-o</option>
<option {{  $selected == 'fa fa-bullhorn' ? 'selected' : '' }} value='fa fa-bullhorn'>&#xf0a1; bullhorn</option>
<option {{  $selected == 'fa fa-bullseye' ? 'selected' : '' }} value='fa fa-bullseye'>&#xf140; bullseye</option>
<option {{  $selected == 'fa fa-bus' ? 'selected' : '' }} value='fa fa-bus'>&#xf207; bus</option>
<option {{  $selected == 'fa fa-buysellads' ? 'selected' : '' }} value='fa fa-buysellads'>&#xf20d; buysellads</option>
<option {{  $selected == 'fa fa-cab' ? 'selected' : '' }} value='fa fa-cab'>&#xf1ba; cab</option>
<option {{  $selected == 'fa fa-calculator' ? 'selected' : '' }} value='fa fa-calculator'>&#xf1ec; calculator</option>
<option {{  $selected == 'fa fa-calendar' ? 'selected' : '' }} value='fa fa-calendar'>&#xf073; calendar</option>
<option {{  $selected == 'fa fa-calendar-check-o' ? 'selected' : '' }} value='fa fa-calendar-check-o'>&#xf274; calendar-check-o</option>
<option {{  $selected == 'fa fa-calendar-minus-o' ? 'selected' : '' }} value='fa fa-calendar-minus-o'>&#xf272; calendar-minus-o</option>
<option {{  $selected == 'fa fa-calendar-o' ? 'selected' : '' }} value='fa fa-calendar-o'>&#xf133; calendar-o</option>
<option {{  $selected == 'fa fa-calendar-plus-o' ? 'selected' : '' }} value='fa fa-calendar-plus-o'>&#xf271; calendar-plus-o</option>
<option {{  $selected == 'fa fa-calendar-times-o' ? 'selected' : '' }} value='fa fa-calendar-times-o'>&#xf273; calendar-times-o</option>
<option {{  $selected == 'fa fa-camera' ? 'selected' : '' }} value='fa fa-camera'>&#xf030; camera</option>
<option {{  $selected == 'fa fa-camera-retro' ? 'selected' : '' }} value='fa fa-camera-retro'>&#xf083; camera-retro</option>
<option {{  $selected == 'fa fa-car' ? 'selected' : '' }} value='fa fa-car'>&#xf1b9; car</option>
<option {{  $selected == 'fa fa-caret-down' ? 'selected' : '' }} value='fa fa-caret-down'>&#xf0d7; caret-down</option>
<option {{  $selected == 'fa fa-caret-left' ? 'selected' : '' }} value='fa fa-caret-left'>&#xf0d9; caret-left</option>
<option {{  $selected == 'fa fa-caret-right' ? 'selected' : '' }} value='fa fa-caret-right'>&#xf0da; caret-right</option>
<option {{  $selected == 'fa fa-caret-square-o-down' ? 'selected' : '' }} value='fa fa-caret-square-o-down'>&#xf150; caret-square-o-down</option>
<option {{  $selected == 'fa fa-caret-square-o-left' ? 'selected' : '' }} value='fa fa-caret-square-o-left'>&#xf191; caret-square-o-left</option>
<option {{  $selected == 'fa fa-caret-square-o-right' ? 'selected' : '' }} value='fa fa-caret-square-o-right'>&#xf152; caret-square-o-right</option>
<option {{  $selected == 'fa fa-caret-square-o-up' ? 'selected' : '' }} value='fa fa-caret-square-o-up'>&#xf151; caret-square-o-up</option>
<option {{  $selected == 'fa fa-caret-up' ? 'selected' : '' }} value='fa fa-caret-up'>&#xf0d8; caret-up</option>
<option {{  $selected == 'fa fa-cart-arrow-down' ? 'selected' : '' }} value='fa fa-cart-arrow-down'>&#xf218; cart-arrow-down</option>
<option {{  $selected == 'fa fa-cart-plus' ? 'selected' : '' }} value='fa fa-cart-plus'>&#xf217; cart-plus</option>
<option {{  $selected == 'fa fa-cc' ? 'selected' : '' }} value='fa fa-cc'>&#xf20a; cc</option>
<option {{  $selected == 'fa fa-cc-amex' ? 'selected' : '' }} value='fa fa-cc-amex'>&#xf1f3; cc-amex</option>
<option {{  $selected == 'fa fa-cc-diners-club' ? 'selected' : '' }} value='fa fa-cc-diners-club'>&#xf24c; cc-diners-club</option>
<option {{  $selected == 'fa fa-cc-discover' ? 'selected' : '' }} value='fa fa-cc-discover'>&#xf1f2; cc-discover</option>
<option {{  $selected == 'fa fa-cc-jcb' ? 'selected' : '' }} value='fa fa-cc-jcb'>&#xf24b; cc-jcb</option>
<option {{  $selected == 'fa fa-cc-mastercard' ? 'selected' : '' }} value='fa fa-cc-mastercard'>&#xf1f1; cc-mastercard</option>
<option {{  $selected == 'fa fa-cc-paypal' ? 'selected' : '' }} value='fa fa-cc-paypal'>&#xf1f4; cc-paypal</option>
<option {{  $selected == 'fa fa-cc-stripe' ? 'selected' : '' }} value='fa fa-cc-stripe'>&#xf1f5; cc-stripe</option>
<option {{  $selected == 'fa fa-cc-visa' ? 'selected' : '' }} value='fa fa-cc-visa'>&#xf1f0; cc-visa</option>
<option {{  $selected == 'fa fa-certificate' ? 'selected' : '' }} value='fa fa-certificate'>&#xf0a3; certificate</option>
<option {{  $selected == 'fa fa-chain' ? 'selected' : '' }} value='fa fa-chain'>&#xf0c1; chain</option>
<option {{  $selected == 'fa fa-chain-broken' ? 'selected' : '' }} value='fa fa-chain-broken'>&#xf127; chain-broken</option>
<option {{  $selected == 'fa fa-check' ? 'selected' : '' }} value='fa fa-check'>&#xf00c; check</option>
<option {{  $selected == 'fa fa-check-circle' ? 'selected' : '' }} value='fa fa-check-circle'>&#xf058; check-circle</option>
<option {{  $selected == 'fa fa-check-circle-o' ? 'selected' : '' }} value='fa fa-check-circle-o'>&#xf05d; check-circle-o</option>
<option {{  $selected == 'fa fa-check-square' ? 'selected' : '' }} value='fa fa-check-square'>&#xf14a; check-square</option>
<option {{  $selected == 'fa fa-check-square-o' ? 'selected' : '' }} value='fa fa-check-square-o'>&#xf046; check-square-o</option>
<option {{  $selected == 'fa fa-chevron-circle-down' ? 'selected' : '' }} value='fa fa-chevron-circle-down'>&#xf13a; chevron-circle-down</option>
<option {{  $selected == 'fa fa-chevron-circle-left' ? 'selected' : '' }} value='fa fa-chevron-circle-left'>&#xf137; chevron-circle-left</option>
<option {{  $selected == 'fa fa-chevron-circle-right' ? 'selected' : '' }} value='fa fa-chevron-circle-right'>&#xf138; chevron-circle-right</option>
<option {{  $selected == 'fa fa-chevron-circle-up' ? 'selected' : '' }} value='fa fa-chevron-circle-up'>&#xf139; chevron-circle-up</option>
<option {{  $selected == 'fa fa-chevron-down' ? 'selected' : '' }} value='fa fa-chevron-down'>&#xf078; chevron-down</option>
<option {{  $selected == 'fa fa-chevron-left' ? 'selected' : '' }} value='fa fa-chevron-left'>&#xf053; chevron-left</option>
<option {{  $selected == 'fa fa-chevron-right' ? 'selected' : '' }} value='fa fa-chevron-right'>&#xf054; chevron-right</option>
<option {{  $selected == 'fa fa-chevron-up' ? 'selected' : '' }} value='fa fa-chevron-up'>&#xf077; chevron-up</option>
<option {{  $selected == 'fa fa-child' ? 'selected' : '' }} value='fa fa-child'>&#xf1ae; child</option>
<option {{  $selected == 'fa fa-chrome' ? 'selected' : '' }} value='fa fa-chrome'>&#xf268; chrome</option>
<option {{  $selected == 'fa fa-circle' ? 'selected' : '' }} value='fa fa-circle'>&#xf111; circle</option>
<option {{  $selected == 'fa fa-circle-o' ? 'selected' : '' }} value='fa fa-circle-o'>&#xf10c; circle-o</option>
<option {{  $selected == 'fa fa-circle-o-notch' ? 'selected' : '' }} value='fa fa-circle-o-notch'>&#xf1ce; circle-o-notch</option>
<option {{  $selected == 'fa fa-circle-thin' ? 'selected' : '' }} value='fa fa-circle-thin'>&#xf1db; circle-thin</option>
<option {{  $selected == 'fa fa-clipboard' ? 'selected' : '' }} value='fa fa-clipboard'>&#xf0ea; clipboard</option>
<option {{  $selected == 'fa fa-clock-o' ? 'selected' : '' }} value='fa fa-clock-o'>&#xf017; clock-o</option>
<option {{  $selected == 'fa fa-clone' ? 'selected' : '' }} value='fa fa-clone'>&#xf24d; clone</option>
<option {{  $selected == 'fa fa-close' ? 'selected' : '' }} value='fa fa-close'>&#xf00d; close</option>
<option {{  $selected == 'fa fa-cloud' ? 'selected' : '' }} value='fa fa-cloud'>&#xf0c2; cloud</option>
<option {{  $selected == 'fa fa-cloud-download' ? 'selected' : '' }} value='fa fa-cloud-download'>&#xf0ed; cloud-download</option>
<option {{  $selected == 'fa fa-cloud-upload' ? 'selected' : '' }} value='fa fa-cloud-upload'>&#xf0ee; cloud-upload</option>
<option {{  $selected == 'fa fa-cny' ? 'selected' : '' }} value='fa fa-cny'>&#xf157; cny</option>
<option {{  $selected == 'fa fa-code' ? 'selected' : '' }} value='fa fa-code'>&#xf121; code</option>
<option {{  $selected == 'fa fa-code-fork' ? 'selected' : '' }} value='fa fa-code-fork'>&#xf126; code-fork</option>
<option {{  $selected == 'fa fa-codepen' ? 'selected' : '' }} value='fa fa-codepen'>&#xf1cb; codepen</option>
<option {{  $selected == 'fa fa-codiepie' ? 'selected' : '' }} value='fa fa-codiepie'>&#xf284; codiepie</option>
<option {{  $selected == 'fa fa-coffee' ? 'selected' : '' }} value='fa fa-coffee'>&#xf0f4; coffee</option>
<option {{  $selected == 'fa fa-cog' ? 'selected' : '' }} value='fa fa-cog'>&#xf013; cog</option>
<option {{  $selected == 'fa fa-cogs' ? 'selected' : '' }} value='fa fa-cogs'>&#xf085; cogs</option>
<option {{  $selected == 'fa fa-columns' ? 'selected' : '' }} value='fa fa-columns'>&#xf0db; columns</option>
<option {{  $selected == 'fa fa-comment' ? 'selected' : '' }} value='fa fa-comment'>&#xf075; comment</option>
<option {{  $selected == 'fa fa-comment-o' ? 'selected' : '' }} value='fa fa-comment-o'>&#xf0e5; comment-o</option>
<option {{  $selected == 'fa fa-commenting' ? 'selected' : '' }} value='fa fa-commenting'>&#xf27a; commenting</option>
<option {{  $selected == 'fa fa-commenting-o' ? 'selected' : '' }} value='fa fa-commenting-o'>&#xf27b; commenting-o</option>
<option {{  $selected == 'fa fa-comments' ? 'selected' : '' }} value='fa fa-comments'>&#xf086; comments</option>
<option {{  $selected == 'fa fa-comments-o' ? 'selected' : '' }} value='fa fa-comments-o'>&#xf0e6; comments-o</option>
<option {{  $selected == 'fa fa-compass' ? 'selected' : '' }} value='fa fa-compass'>&#xf14e; compass</option>
<option {{  $selected == 'fa fa-compress' ? 'selected' : '' }} value='fa fa-compress'>&#xf066; compress</option>
<option {{  $selected == 'fa fa-connectdevelop' ? 'selected' : '' }} value='fa fa-connectdevelop'>&#xf20e; connectdevelop</option>
<option {{  $selected == 'fa fa-contao' ? 'selected' : '' }} value='fa fa-contao'>&#xf26d; contao</option>
<option {{  $selected == 'fa fa-copy' ? 'selected' : '' }} value='fa fa-copy'>&#xf0c5; copy</option>
<option {{  $selected == 'fa fa-copyright' ? 'selected' : '' }} value='fa fa-copyright'>&#xf1f9; copyright</option>
<option {{  $selected == 'fa fa-creative-commons' ? 'selected' : '' }} value='fa fa-creative-commons'>&#xf25e; creative-commons</option>
<option {{  $selected == 'fa fa-credit-card' ? 'selected' : '' }} value='fa fa-credit-card'>&#xf09d; credit-card</option>
<option {{  $selected == 'fa fa-credit-card-alt' ? 'selected' : '' }} value='fa fa-credit-card-alt'>&#xf283; credit-card-alt</option>
<option {{  $selected == 'fa fa-crop' ? 'selected' : '' }} value='fa fa-crop'>&#xf125; crop</option>
<option {{  $selected == 'fa fa-crosshairs' ? 'selected' : '' }} value='fa fa-crosshairs'>&#xf05b; crosshairs</option>
<option {{  $selected == 'fa fa-css3' ? 'selected' : '' }} value='fa fa-css3'>&#xf13c; css3</option>
<option {{  $selected == 'fa fa-cube' ? 'selected' : '' }} value='fa fa-cube'>&#xf1b2; cube</option>
<option {{  $selected == 'fa fa-cubes' ? 'selected' : '' }} value='fa fa-cubes'>&#xf1b3; cubes</option>
<option {{  $selected == 'fa fa-cut' ? 'selected' : '' }} value='fa fa-cut'>&#xf0c4; cut</option>
<option {{  $selected == 'fa fa-cutlery' ? 'selected' : '' }} value='fa fa-cutlery'>&#xf0f5; cutlery</option>
<option {{  $selected == 'fa fa-dashboard' ? 'selected' : '' }} value='fa fa-dashboard'>&#xf0e4; dashboard</option>
<option {{  $selected == 'fa fa-dashcube' ? 'selected' : '' }} value='fa fa-dashcube'>&#xf210; dashcube</option>
<option {{  $selected == 'fa fa-database' ? 'selected' : '' }} value='fa fa-database'>&#xf1c0; database</option>
<option {{  $selected == 'fa fa-deaf' ? 'selected' : '' }} value='fa fa-deaf'>&#xf2a4; deaf</option>
<option {{  $selected == 'fa fa-deafness' ? 'selected' : '' }} value='fa fa-deafness'>&#xf2a4; deafness</option>
<option {{  $selected == 'fa fa-dedent' ? 'selected' : '' }} value='fa fa-dedent'>&#xf03b; dedent</option>
<option {{  $selected == 'fa fa-delicious' ? 'selected' : '' }} value='fa fa-delicious'>&#xf1a5; delicious</option>
<option {{  $selected == 'fa fa-desktop' ? 'selected' : '' }} value='fa fa-desktop'>&#xf108; desktop</option>
<option {{  $selected == 'fa fa-deviantart' ? 'selected' : '' }} value='fa fa-deviantart'>&#xf1bd; deviantart</option>
<option {{  $selected == 'fa fa-diamond' ? 'selected' : '' }} value='fa fa-diamond'>&#xf219; diamond</option>
<option {{  $selected == 'fa fa-digg' ? 'selected' : '' }} value='fa fa-digg'>&#xf1a6; digg</option>
<option {{  $selected == 'fa fa-dollar' ? 'selected' : '' }} value='fa fa-dollar'>&#xf155; dollar</option>
<option {{  $selected == 'fa fa-dot-circle-o' ? 'selected' : '' }} value='fa fa-dot-circle-o'>&#xf192; dot-circle-o</option>
<option {{  $selected == 'fa fa-download' ? 'selected' : '' }} value='fa fa-download'>&#xf019; download</option>
<option {{  $selected == 'fa fa-dribbble' ? 'selected' : '' }} value='fa fa-dribbble'>&#xf17d; dribbble</option>
<option {{  $selected == 'fa fa-drivers-license' ? 'selected' : '' }} value='fa fa-drivers-license'>&#xf2c2; drivers-license</option>
<option {{  $selected == 'fa fa-drivers-license-o' ? 'selected' : '' }} value='fa fa-drivers-license-o'>&#xf2c3; drivers-license-o</option>
<option {{  $selected == 'fa fa-dropbox' ? 'selected' : '' }} value='fa fa-dropbox'>&#xf16b; dropbox</option>
<option {{  $selected == 'fa fa-drupal' ? 'selected' : '' }} value='fa fa-drupal'>&#xf1a9; drupal</option>
<option {{  $selected == 'fa fa-edge' ? 'selected' : '' }} value='fa fa-edge'>&#xf282; edge</option>
<option {{  $selected == 'fa fa-edit' ? 'selected' : '' }} value='fa fa-edit'>&#xf044; edit</option>
<option {{  $selected == 'fa fa-eercast' ? 'selected' : '' }} value='fa fa-eercast'>&#xf2da; eercast</option>
<option {{  $selected == 'fa fa-eject' ? 'selected' : '' }} value='fa fa-eject'>&#xf052; eject</option>
<option {{  $selected == 'fa fa-ellipsis-h' ? 'selected' : '' }} value='fa fa-ellipsis-h'>&#xf141; ellipsis-h</option>
<option {{  $selected == 'fa fa-ellipsis-v' ? 'selected' : '' }} value='fa fa-ellipsis-v'>&#xf142; ellipsis-v</option>
<option {{  $selected == 'fa fa-empire' ? 'selected' : '' }} value='fa fa-empire'>&#xf1d1; empire</option>
<option {{  $selected == 'fa fa-envelope' ? 'selected' : '' }} value='fa fa-envelope'>&#xf0e0; envelope</option>
<option {{  $selected == 'fa fa-envelope-o' ? 'selected' : '' }} value='fa fa-envelope-o'>&#xf003; envelope-o</option>
<option {{  $selected == 'fa fa-envelope-open' ? 'selected' : '' }} value='fa fa-envelope-open'>&#xf2b6; envelope-open</option>
<option {{  $selected == 'fa fa-envelope-open-o' ? 'selected' : '' }} value='fa fa-envelope-open-o'>&#xf2b7; envelope-open-o</option>
<option {{  $selected == 'fa fa-envelope-square' ? 'selected' : '' }} value='fa fa-envelope-square'>&#xf199; envelope-square</option>
<option {{  $selected == 'fa fa-envira' ? 'selected' : '' }} value='fa fa-envira'>&#xf299; envira</option>
<option {{  $selected == 'fa fa-eraser' ? 'selected' : '' }} value='fa fa-eraser'>&#xf12d; eraser</option>
<option {{  $selected == 'fa fa-etsy' ? 'selected' : '' }} value='fa fa-etsy'>&#xf2d7; etsy</option>
<option {{  $selected == 'fa fa-eur' ? 'selected' : '' }} value='fa fa-eur'>&#xf153; eur</option>
<option {{  $selected == 'fa fa-euro' ? 'selected' : '' }} value='fa fa-euro'>&#xf153; euro</option>
<option {{  $selected == 'fa fa-exchange' ? 'selected' : '' }} value='fa fa-exchange'>&#xf0ec; exchange</option>
<option {{  $selected == 'fa fa-exclamation' ? 'selected' : '' }} value='fa fa-exclamation'>&#xf12a; exclamation</option>
<option {{  $selected == 'fa fa-exclamation-circle' ? 'selected' : '' }} value='fa fa-exclamation-circle'>&#xf06a; exclamation-circle</option>
<option {{  $selected == 'fa fa-exclamation-triangle' ? 'selected' : '' }} value='fa fa-exclamation-triangle'>&#xf071; exclamation-triangle</option>
<option {{  $selected == 'fa fa-expand' ? 'selected' : '' }} value='fa fa-expand'>&#xf065; expand</option>
<option {{  $selected == 'fa fa-expeditedssl' ? 'selected' : '' }} value='fa fa-expeditedssl'>&#xf23e; expeditedssl</option>
<option {{  $selected == 'fa fa-external-link' ? 'selected' : '' }} value='fa fa-external-link'>&#xf08e; external-link</option>
<option {{  $selected == 'fa fa-external-link-square' ? 'selected' : '' }} value='fa fa-external-link-square'>&#xf14c; external-link-square</option>
<option {{  $selected == 'fa fa-eye' ? 'selected' : '' }} value='fa fa-eye'>&#xf06e; eye</option>
<option {{  $selected == 'fa fa-eye-slash' ? 'selected' : '' }} value='fa fa-eye-slash'>&#xf070; eye-slash</option>
<option {{  $selected == 'fa fa-eyedropper' ? 'selected' : '' }} value='fa fa-eyedropper'>&#xf1fb; eyedropper</option>
<option {{  $selected == 'fa fa-fa' ? 'selected' : '' }} value='fa fa-fa'>&#xf2b4; fa</option>
<option {{  $selected == 'fa fa-facebook' ? 'selected' : '' }} value='fa fa-facebook'>&#xf09a; facebook</option>
<option {{  $selected == 'fa fa-facebook-f' ? 'selected' : '' }} value='fa fa-facebook-f'>&#xf09a; facebook-f</option>
<option {{  $selected == 'fa fa-facebook-official' ? 'selected' : '' }} value='fa fa-facebook-official'>&#xf230; facebook-official</option>
<option {{  $selected == 'fa fa-facebook-square' ? 'selected' : '' }} value='fa fa-facebook-square'>&#xf082; facebook-square</option>
<option {{  $selected == 'fa fa-fast-backward' ? 'selected' : '' }} value='fa fa-fast-backward'>&#xf049; fast-backward</option>
<option {{  $selected == 'fa fa-fast-forward' ? 'selected' : '' }} value='fa fa-fast-forward'>&#xf050; fast-forward</option>
<option {{  $selected == 'fa fa-fax' ? 'selected' : '' }} value='fa fa-fax'>&#xf1ac; fax</option>
<option {{  $selected == 'fa fa-feed' ? 'selected' : '' }} value='fa fa-feed'>&#xf09e; feed</option>
<option {{  $selected == 'fa fa-female' ? 'selected' : '' }} value='fa fa-female'>&#xf182; female</option>
<option {{  $selected == 'fa fa-fighter-jet' ? 'selected' : '' }} value='fa fa-fighter-jet'>&#xf0fb; fighter-jet</option>
<option {{  $selected == 'fa fa-file' ? 'selected' : '' }} value='fa fa-file'>&#xf15b; file</option>
<option {{  $selected == 'fa fa-file-archive-o' ? 'selected' : '' }} value='fa fa-file-archive-o'>&#xf1c6; file-archive-o</option>
<option {{  $selected == 'fa fa-file-audio-o' ? 'selected' : '' }} value='fa fa-file-audio-o'>&#xf1c7; file-audio-o</option>
<option {{  $selected == 'fa fa-file-code-o' ? 'selected' : '' }} value='fa fa-file-code-o'>&#xf1c9; file-code-o</option>
<option {{  $selected == 'fa fa-file-excel-o' ? 'selected' : '' }} value='fa fa-file-excel-o'>&#xf1c3; file-excel-o</option>
<option {{  $selected == 'fa fa-file-image-o' ? 'selected' : '' }} value='fa fa-file-image-o'>&#xf1c5; file-image-o</option>
<option {{  $selected == 'fa fa-file-movie-o' ? 'selected' : '' }} value='fa fa-file-movie-o'>&#xf1c8; file-movie-o</option>
<option {{  $selected == 'fa fa-file-o' ? 'selected' : '' }} value='fa fa-file-o'>&#xf016; file-o</option>
<option {{  $selected == 'fa fa-file-pdf-o' ? 'selected' : '' }} value='fa fa-file-pdf-o'>&#xf1c1; file-pdf-o</option>
<option {{  $selected == 'fa fa-file-photo-o' ? 'selected' : '' }} value='fa fa-file-photo-o'>&#xf1c5; file-photo-o</option>
<option {{  $selected == 'fa fa-file-picture-o' ? 'selected' : '' }} value='fa fa-file-picture-o'>&#xf1c5; file-picture-o</option>
<option {{  $selected == 'fa fa-file-powerpoint-o' ? 'selected' : '' }} value='fa fa-file-powerpoint-o'>&#xf1c4; file-powerpoint-o</option>
<option {{  $selected == 'fa fa-file-sound-o' ? 'selected' : '' }} value='fa fa-file-sound-o'>&#xf1c7; file-sound-o</option>
<option {{  $selected == 'fa fa-file-text' ? 'selected' : '' }} value='fa fa-file-text'>&#xf15c; file-text</option>
<option {{  $selected == 'fa fa-file-text-o' ? 'selected' : '' }} value='fa fa-file-text-o'>&#xf0f6; file-text-o</option>
<option {{  $selected == 'fa fa-file-video-o' ? 'selected' : '' }} value='fa fa-file-video-o'>&#xf1c8; file-video-o</option>
<option {{  $selected == 'fa fa-file-word-o' ? 'selected' : '' }} value='fa fa-file-word-o'>&#xf1c2; file-word-o</option>
<option {{  $selected == 'fa fa-file-zip-o' ? 'selected' : '' }} value='fa fa-file-zip-o'>&#xf1c6; file-zip-o</option>
<option {{  $selected == 'fa fa-files-o' ? 'selected' : '' }} value='fa fa-files-o'>&#xf0c5; files-o</option>
<option {{  $selected == 'fa fa-film' ? 'selected' : '' }} value='fa fa-film'>&#xf008; film</option>
<option {{  $selected == 'fa fa-filter' ? 'selected' : '' }} value='fa fa-filter'>&#xf0b0; filter</option>
<option {{  $selected == 'fa fa-fire' ? 'selected' : '' }} value='fa fa-fire'>&#xf06d; fire</option>
<option {{  $selected == 'fa fa-fire-extinguisher' ? 'selected' : '' }} value='fa fa-fire-extinguisher'>&#xf134; fire-extinguisher</option>
<option {{  $selected == 'fa fa-firefox' ? 'selected' : '' }} value='fa fa-firefox'>&#xf269; firefox</option>
<option {{  $selected == 'fa fa-first-order' ? 'selected' : '' }} value='fa fa-first-order'>&#xf2b0; first-order</option>
<option {{  $selected == 'fa fa-flag' ? 'selected' : '' }} value='fa fa-flag'>&#xf024; flag</option>
<option {{  $selected == 'fa fa-flag-checkered' ? 'selected' : '' }} value='fa fa-flag-checkered'>&#xf11e; flag-checkered</option>
<option {{  $selected == 'fa fa-flag-o' ? 'selected' : '' }} value='fa fa-flag-o'>&#xf11d; flag-o</option>
<option {{  $selected == 'fa fa-flash' ? 'selected' : '' }} value='fa fa-flash'>&#xf0e7; flash</option>
<option {{  $selected == 'fa fa-flask' ? 'selected' : '' }} value='fa fa-flask'>&#xf0c3; flask</option>
<option {{  $selected == 'fa fa-flickr' ? 'selected' : '' }} value='fa fa-flickr'>&#xf16e; flickr</option>
<option {{  $selected == 'fa fa-floppy-o' ? 'selected' : '' }} value='fa fa-floppy-o'>&#xf0c7; floppy-o</option>
<option {{  $selected == 'fa fa-folder' ? 'selected' : '' }} value='fa fa-folder'>&#xf07b; folder</option>
<option {{  $selected == 'fa fa-folder-o' ? 'selected' : '' }} value='fa fa-folder-o'>&#xf114; folder-o</option>
<option {{  $selected == 'fa fa-folder-open' ? 'selected' : '' }} value='fa fa-folder-open'>&#xf07c; folder-open</option>
<option {{  $selected == 'fa fa-folder-open-o' ? 'selected' : '' }} value='fa fa-folder-open-o'>&#xf115; folder-open-o</option>
<option {{  $selected == 'fa fa-font' ? 'selected' : '' }} value='fa fa-font'>&#xf031; font</option>
<option {{  $selected == 'fa fa-font-awesome' ? 'selected' : '' }} value='fa fa-font-awesome'>&#xf2b4; font-awesome</option>
<option {{  $selected == 'fa fa-fonticons' ? 'selected' : '' }} value='fa fa-fonticons'>&#xf280; fonticons</option>
<option {{  $selected == 'fa fa-fort-awesome' ? 'selected' : '' }} value='fa fa-fort-awesome'>&#xf286; fort-awesome</option>
<option {{  $selected == 'fa fa-forumbee' ? 'selected' : '' }} value='fa fa-forumbee'>&#xf211; forumbee</option>
<option {{  $selected == 'fa fa-forward' ? 'selected' : '' }} value='fa fa-forward'>&#xf04e; forward</option>
<option {{  $selected == 'fa fa-foursquare' ? 'selected' : '' }} value='fa fa-foursquare'>&#xf180; foursquare</option>
<option {{  $selected == 'fa fa-free-code-camp' ? 'selected' : '' }} value='fa fa-free-code-camp'>&#xf2c5; free-code-camp</option>
<option {{  $selected == 'fa fa-frown-o' ? 'selected' : '' }} value='fa fa-frown-o'>&#xf119; frown-o</option>
<option {{  $selected == 'fa fa-futbol-o' ? 'selected' : '' }} value='fa fa-futbol-o'>&#xf1e3; futbol-o</option>
<option {{  $selected == 'fa fa-gamepad' ? 'selected' : '' }} value='fa fa-gamepad'>&#xf11b; gamepad</option>
<option {{  $selected == 'fa fa-gavel' ? 'selected' : '' }} value='fa fa-gavel'>&#xf0e3; gavel</option>
<option {{  $selected == 'fa fa-gbp' ? 'selected' : '' }} value='fa fa-gbp'>&#xf154; gbp</option>
<option {{  $selected == 'fa fa-ge' ? 'selected' : '' }} value='fa fa-ge'>&#xf1d1; ge</option>
<option {{  $selected == 'fa fa-gear' ? 'selected' : '' }} value='fa fa-gear'>&#xf013; gear</option>
<option {{  $selected == 'fa fa-gears' ? 'selected' : '' }} value='fa fa-gears'>&#xf085; gears</option>
<option {{  $selected == 'fa fa-genderless' ? 'selected' : '' }} value='fa fa-genderless'>&#xf22d; genderless</option>
<option {{  $selected == 'fa fa-get-pocket' ? 'selected' : '' }} value='fa fa-get-pocket'>&#xf265; get-pocket</option>
<option {{  $selected == 'fa fa-gg' ? 'selected' : '' }} value='fa fa-gg'>&#xf260; gg</option>
<option {{  $selected == 'fa fa-gg-circle' ? 'selected' : '' }} value='fa fa-gg-circle'>&#xf261; gg-circle</option>
<option {{  $selected == 'fa fa-gift' ? 'selected' : '' }} value='fa fa-gift'>&#xf06b; gift</option>
<option {{  $selected == 'fa fa-git' ? 'selected' : '' }} value='fa fa-git'>&#xf1d3; git</option>
<option {{  $selected == 'fa fa-git-square' ? 'selected' : '' }} value='fa fa-git-square'>&#xf1d2; git-square</option>
<option {{  $selected == 'fa fa-github' ? 'selected' : '' }} value='fa fa-github'>&#xf09b; github</option>
<option {{  $selected == 'fa fa-github-alt' ? 'selected' : '' }} value='fa fa-github-alt'>&#xf113; github-alt</option>
<option {{  $selected == 'fa fa-github-square' ? 'selected' : '' }} value='fa fa-github-square'>&#xf092; github-square</option>
<option {{  $selected == 'fa fa-gitlab' ? 'selected' : '' }} value='fa fa-gitlab'>&#xf296; gitlab</option>
<option {{  $selected == 'fa fa-gittip' ? 'selected' : '' }} value='fa fa-gittip'>&#xf184; gittip</option>
<option {{  $selected == 'fa fa-glass' ? 'selected' : '' }} value='fa fa-glass'>&#xf000; glass</option>
<option {{  $selected == 'fa fa-glide' ? 'selected' : '' }} value='fa fa-glide'>&#xf2a5; glide</option>
<option {{  $selected == 'fa fa-glide-g' ? 'selected' : '' }} value='fa fa-glide-g'>&#xf2a6; glide-g</option>
<option {{  $selected == 'fa fa-globe' ? 'selected' : '' }} value='fa fa-globe'>&#xf0ac; globe</option>
<option {{  $selected == 'fa fa-google' ? 'selected' : '' }} value='fa fa-google'>&#xf1a0; google</option>
<option {{  $selected == 'fa fa-google-plus' ? 'selected' : '' }} value='fa fa-google-plus'>&#xf0d5; google-plus</option>
<option {{  $selected == 'fa fa-google-plus-circle' ? 'selected' : '' }} value='fa fa-google-plus-circle'>&#xf2b3; google-plus-circle</option>
<option {{  $selected == 'fa fa-google-plus-official' ? 'selected' : '' }} value='fa fa-google-plus-official'>&#xf2b3; google-plus-official</option>
<option {{  $selected == 'fa fa-google-plus-square' ? 'selected' : '' }} value='fa fa-google-plus-square'>&#xf0d4; google-plus-square</option>
<option {{  $selected == 'fa fa-google-wallet' ? 'selected' : '' }} value='fa fa-google-wallet'>&#xf1ee; google-wallet</option>
<option {{  $selected == 'fa fa-graduation-cap' ? 'selected' : '' }} value='fa fa-graduation-cap'>&#xf19d; graduation-cap</option>
<option {{  $selected == 'fa fa-gratipay' ? 'selected' : '' }} value='fa fa-gratipay'>&#xf184; gratipay</option>
<option {{  $selected == 'fa fa-grav' ? 'selected' : '' }} value='fa fa-grav'>&#xf2d6; grav</option>
<option {{  $selected == 'fa fa-group' ? 'selected' : '' }} value='fa fa-group'>&#xf0c0; group</option>
<option {{  $selected == 'fa fa-h-square' ? 'selected' : '' }} value='fa fa-h-square'>&#xf0fd; h-square</option>
<option {{  $selected == 'fa fa-hacker-news' ? 'selected' : '' }} value='fa fa-hacker-news'>&#xf1d4; hacker-news</option>
<option {{  $selected == 'fa fa-hand-grab-o' ? 'selected' : '' }} value='fa fa-hand-grab-o'>&#xf255; hand-grab-o</option>
<option {{  $selected == 'fa fa-hand-lizard-o' ? 'selected' : '' }} value='fa fa-hand-lizard-o'>&#xf258; hand-lizard-o</option>
<option {{  $selected == 'fa fa-hand-o-down' ? 'selected' : '' }} value='fa fa-hand-o-down'>&#xf0a7; hand-o-down</option>
<option {{  $selected == 'fa fa-hand-o-left' ? 'selected' : '' }} value='fa fa-hand-o-left'>&#xf0a5; hand-o-left</option>
<option {{  $selected == 'fa fa-hand-o-right' ? 'selected' : '' }} value='fa fa-hand-o-right'>&#xf0a4; hand-o-right</option>
<option {{  $selected == 'fa fa-hand-o-up' ? 'selected' : '' }} value='fa fa-hand-o-up'>&#xf0a6; hand-o-up</option>
<option {{  $selected == 'fa fa-hand-paper-o' ? 'selected' : '' }} value='fa fa-hand-paper-o'>&#xf256; hand-paper-o</option>
<option {{  $selected == 'fa fa-hand-peace-o' ? 'selected' : '' }} value='fa fa-hand-peace-o'>&#xf25b; hand-peace-o</option>
<option {{  $selected == 'fa fa-hand-pointer-o' ? 'selected' : '' }} value='fa fa-hand-pointer-o'>&#xf25a; hand-pointer-o</option>
<option {{  $selected == 'fa fa-hand-rock-o' ? 'selected' : '' }} value='fa fa-hand-rock-o'>&#xf255; hand-rock-o</option>
<option {{  $selected == 'fa fa-hand-scissors-o' ? 'selected' : '' }} value='fa fa-hand-scissors-o'>&#xf257; hand-scissors-o</option>
<option {{  $selected == 'fa fa-hand-spock-o' ? 'selected' : '' }} value='fa fa-hand-spock-o'>&#xf259; hand-spock-o</option>
<option {{  $selected == 'fa fa-hand-stop-o' ? 'selected' : '' }} value='fa fa-hand-stop-o'>&#xf256; hand-stop-o</option>
<option {{  $selected == 'fa fa-handshake-o' ? 'selected' : '' }} value='fa fa-handshake-o'>&#xf2b5; handshake-o</option>
<option {{  $selected == 'fa fa-hard-of-hearing' ? 'selected' : '' }} value='fa fa-hard-of-hearing'>&#xf2a4; hard-of-hearing</option>
<option {{  $selected == 'fa fa-hashtag' ? 'selected' : '' }} value='fa fa-hashtag'>&#xf292; hashtag</option>
<option {{  $selected == 'fa fa-hdd-o' ? 'selected' : '' }} value='fa fa-hdd-o'>&#xf0a0; hdd-o</option>
<option {{  $selected == 'fa fa-header' ? 'selected' : '' }} value='fa fa-header'>&#xf1dc; header</option>
<option {{  $selected == 'fa fa-headphones' ? 'selected' : '' }} value='fa fa-headphones'>&#xf025; headphones</option>
<option {{  $selected == 'fa fa-heart' ? 'selected' : '' }} value='fa fa-heart'>&#xf004; heart</option>
<option {{  $selected == 'fa fa-heart-o' ? 'selected' : '' }} value='fa fa-heart-o'>&#xf08a; heart-o</option>
<option {{  $selected == 'fa fa-heartbeat' ? 'selected' : '' }} value='fa fa-heartbeat'>&#xf21e; heartbeat</option>
<option {{  $selected == 'fa fa-history' ? 'selected' : '' }} value='fa fa-history'>&#xf1da; history</option>
<option {{  $selected == 'fa fa-home' ? 'selected' : '' }} value='fa fa-home'>&#xf015; home</option>
<option {{  $selected == 'fa fa-hospital-o' ? 'selected' : '' }} value='fa fa-hospital-o'>&#xf0f8; hospital-o</option>
<option {{  $selected == 'fa fa-hotel' ? 'selected' : '' }} value='fa fa-hotel'>&#xf236; hotel</option>
<option {{  $selected == 'fa fa-hourglass' ? 'selected' : '' }} value='fa fa-hourglass'>&#xf254; hourglass</option>
<option {{  $selected == 'fa fa-hourglass-1' ? 'selected' : '' }} value='fa fa-hourglass-1'>&#xf251; hourglass-1</option>
<option {{  $selected == 'fa fa-hourglass-2' ? 'selected' : '' }} value='fa fa-hourglass-2'>&#xf252; hourglass-2</option>
<option {{  $selected == 'fa fa-hourglass-3' ? 'selected' : '' }} value='fa fa-hourglass-3'>&#xf253; hourglass-3</option>
<option {{  $selected == 'fa fa-hourglass-end' ? 'selected' : '' }} value='fa fa-hourglass-end'>&#xf253; hourglass-end</option>
<option {{  $selected == 'fa fa-hourglass-half' ? 'selected' : '' }} value='fa fa-hourglass-half'>&#xf252; hourglass-half</option>
<option {{  $selected == 'fa fa-hourglass-o' ? 'selected' : '' }} value='fa fa-hourglass-o'>&#xf250; hourglass-o</option>
<option {{  $selected == 'fa fa-hourglass-start' ? 'selected' : '' }} value='fa fa-hourglass-start'>&#xf251; hourglass-start</option>
<option {{  $selected == 'fa fa-houzz' ? 'selected' : '' }} value='fa fa-houzz'>&#xf27c; houzz</option>
<option {{  $selected == 'fa fa-html5' ? 'selected' : '' }} value='fa fa-html5'>&#xf13b; html5</option>
<option {{  $selected == 'fa fa-i-cursor' ? 'selected' : '' }} value='fa fa-i-cursor'>&#xf246; i-cursor</option>
<option {{  $selected == 'fa fa-id-badge' ? 'selected' : '' }} value='fa fa-id-badge'>&#xf2c1; id-badge</option>
<option {{  $selected == 'fa fa-id-card' ? 'selected' : '' }} value='fa fa-id-card'>&#xf2c2; id-card</option>
<option {{  $selected == 'fa fa-id-card-o' ? 'selected' : '' }} value='fa fa-id-card-o'>&#xf2c3; id-card-o</option>
<option {{  $selected == 'fa fa-ils' ? 'selected' : '' }} value='fa fa-ils'>&#xf20b; ils</option>
<option {{  $selected == 'fa fa-image' ? 'selected' : '' }} value='fa fa-image'>&#xf03e; image</option>
<option {{  $selected == 'fa fa-imdb' ? 'selected' : '' }} value='fa fa-imdb'>&#xf2d8; imdb</option>
<option {{  $selected == 'fa fa-inbox' ? 'selected' : '' }} value='fa fa-inbox'>&#xf01c; inbox</option>
<option {{  $selected == 'fa fa-indent' ? 'selected' : '' }} value='fa fa-indent'>&#xf03c; indent</option>
<option {{  $selected == 'fa fa-industry' ? 'selected' : '' }} value='fa fa-industry'>&#xf275; industry</option>
<option {{  $selected == 'fa fa-info' ? 'selected' : '' }} value='fa fa-info'>&#xf129; info</option>
<option {{  $selected == 'fa fa-info-circle' ? 'selected' : '' }} value='fa fa-info-circle'>&#xf05a; info-circle</option>
<option {{  $selected == 'fa fa-inr' ? 'selected' : '' }} value='fa fa-inr'>&#xf156; inr</option>
<option {{  $selected == 'fa fa-instagram' ? 'selected' : '' }} value='fa fa-instagram'>&#xf16d; instagram</option>
<option {{  $selected == 'fa fa-institution' ? 'selected' : '' }} value='fa fa-institution'>&#xf19c; institution</option>
<option {{  $selected == 'fa fa-internet-explorer' ? 'selected' : '' }} value='fa fa-internet-explorer'>&#xf26b; internet-explorer</option>
<option {{  $selected == 'fa fa-intersex' ? 'selected' : '' }} value='fa fa-intersex'>&#xf224; intersex</option>
<option {{  $selected == 'fa fa-ioxhost' ? 'selected' : '' }} value='fa fa-ioxhost'>&#xf208; ioxhost</option>
<option {{  $selected == 'fa fa-italic' ? 'selected' : '' }} value='fa fa-italic'>&#xf033; italic</option>
<option {{  $selected == 'fa fa-joomla' ? 'selected' : '' }} value='fa fa-joomla'>&#xf1aa; joomla</option>
<option {{  $selected == 'fa fa-jpy' ? 'selected' : '' }} value='fa fa-jpy'>&#xf157; jpy</option>
<option {{  $selected == 'fa fa-jsfiddle' ? 'selected' : '' }} value='fa fa-jsfiddle'>&#xf1cc; jsfiddle</option>
<option {{  $selected == 'fa fa-key' ? 'selected' : '' }} value='fa fa-key'>&#xf084; key</option>
<option {{  $selected == 'fa fa-keyboard-o' ? 'selected' : '' }} value='fa fa-keyboard-o'>&#xf11c; keyboard-o</option>
<option {{  $selected == 'fa fa-krw' ? 'selected' : '' }} value='fa fa-krw'>&#xf159; krw</option>
<option {{  $selected == 'fa fa-language' ? 'selected' : '' }} value='fa fa-language'>&#xf1ab; language</option>
<option {{  $selected == 'fa fa-laptop' ? 'selected' : '' }} value='fa fa-laptop'>&#xf109; laptop</option>
<option {{  $selected == 'fa fa-lastfm' ? 'selected' : '' }} value='fa fa-lastfm'>&#xf202; lastfm</option>
<option {{  $selected == 'fa fa-lastfm-square' ? 'selected' : '' }} value='fa fa-lastfm-square'>&#xf203; lastfm-square</option>
<option {{  $selected == 'fa fa-leaf' ? 'selected' : '' }} value='fa fa-leaf'>&#xf06c; leaf</option>
<option {{  $selected == 'fa fa-leanpub' ? 'selected' : '' }} value='fa fa-leanpub'>&#xf212; leanpub</option>
<option {{  $selected == 'fa fa-legal' ? 'selected' : '' }} value='fa fa-legal'>&#xf0e3; legal</option>
<option {{  $selected == 'fa fa-lemon-o' ? 'selected' : '' }} value='fa fa-lemon-o'>&#xf094; lemon-o</option>
<option {{  $selected == 'fa fa-level-down' ? 'selected' : '' }} value='fa fa-level-down'>&#xf149; level-down</option>
<option {{  $selected == 'fa fa-level-up' ? 'selected' : '' }} value='fa fa-level-up'>&#xf148; level-up</option>
<option {{  $selected == 'fa fa-life-bouy' ? 'selected' : '' }} value='fa fa-life-bouy'>&#xf1cd; life-bouy</option>
<option {{  $selected == 'fa fa-life-buoy' ? 'selected' : '' }} value='fa fa-life-buoy'>&#xf1cd; life-buoy</option>
<option {{  $selected == 'fa fa-life-ring' ? 'selected' : '' }} value='fa fa-life-ring'>&#xf1cd; life-ring</option>
<option {{  $selected == 'fa fa-life-saver' ? 'selected' : '' }} value='fa fa-life-saver'>&#xf1cd; life-saver</option>
<option {{  $selected == 'fa fa-lightbulb-o' ? 'selected' : '' }} value='fa fa-lightbulb-o'>&#xf0eb; lightbulb-o</option>
<option {{  $selected == 'fa fa-line-chart' ? 'selected' : '' }} value='fa fa-line-chart'>&#xf201; line-chart</option>
<option {{  $selected == 'fa fa-link' ? 'selected' : '' }} value='fa fa-link'>&#xf0c1; link</option>
<option {{  $selected == 'fa fa-linkedin' ? 'selected' : '' }} value='fa fa-linkedin'>&#xf0e1; linkedin</option>
<option {{  $selected == 'fa fa-linkedin-square' ? 'selected' : '' }} value='fa fa-linkedin-square'>&#xf08c; linkedin-square</option>
<option {{  $selected == 'fa fa-linode' ? 'selected' : '' }} value='fa fa-linode'>&#xf2b8; linode</option>
<option {{  $selected == 'fa fa-linux' ? 'selected' : '' }} value='fa fa-linux'>&#xf17c; linux</option>
<option {{  $selected == 'fa fa-list' ? 'selected' : '' }} value='fa fa-list'>&#xf03a; list</option>
<option {{  $selected == 'fa fa-list-alt' ? 'selected' : '' }} value='fa fa-list-alt'>&#xf022; list-alt</option>
<option {{  $selected == 'fa fa-list-ol' ? 'selected' : '' }} value='fa fa-list-ol'>&#xf0cb; list-ol</option>
<option {{  $selected == 'fa fa-list-ul' ? 'selected' : '' }} value='fa fa-list-ul'>&#xf0ca; list-ul</option>
<option {{  $selected == 'fa fa-location-arrow' ? 'selected' : '' }} value='fa fa-location-arrow'>&#xf124; location-arrow</option>
<option {{  $selected == 'fa fa-lock' ? 'selected' : '' }} value='fa fa-lock'>&#xf023; lock</option>
<option {{  $selected == 'fa fa-long-arrow-down' ? 'selected' : '' }} value='fa fa-long-arrow-down'>&#xf175; long-arrow-down</option>
<option {{  $selected == 'fa fa-long-arrow-left' ? 'selected' : '' }} value='fa fa-long-arrow-left'>&#xf177; long-arrow-left</option>
<option {{  $selected == 'fa fa-long-arrow-right' ? 'selected' : '' }} value='fa fa-long-arrow-right'>&#xf178; long-arrow-right</option>
<option {{  $selected == 'fa fa-long-arrow-up' ? 'selected' : '' }} value='fa fa-long-arrow-up'>&#xf176; long-arrow-up</option>
<option {{  $selected == 'fa fa-low-vision' ? 'selected' : '' }} value='fa fa-low-vision'>&#xf2a8; low-vision</option>
<option {{  $selected == 'fa fa-magic' ? 'selected' : '' }} value='fa fa-magic'>&#xf0d0; magic</option>
<option {{  $selected == 'fa fa-magnet' ? 'selected' : '' }} value='fa fa-magnet'>&#xf076; magnet</option>
<option {{  $selected == 'fa fa-mail-forward' ? 'selected' : '' }} value='fa fa-mail-forward'>&#xf064; mail-forward</option>
<option {{  $selected == 'fa fa-mail-reply' ? 'selected' : '' }} value='fa fa-mail-reply'>&#xf112; mail-reply</option>
<option {{  $selected == 'fa fa-mail-reply-all' ? 'selected' : '' }} value='fa fa-mail-reply-all'>&#xf122; mail-reply-all</option>
<option {{  $selected == 'fa fa-male' ? 'selected' : '' }} value='fa fa-male'>&#xf183; male</option>
<option {{  $selected == 'fa fa-map' ? 'selected' : '' }} value='fa fa-map'>&#xf279; map</option>
<option {{  $selected == 'fa fa-map-marker' ? 'selected' : '' }} value='fa fa-map-marker'>&#xf041; map-marker</option>
<option {{  $selected == 'fa fa-map-o' ? 'selected' : '' }} value='fa fa-map-o'>&#xf278; map-o</option>
<option {{  $selected == 'fa fa-map-pin' ? 'selected' : '' }} value='fa fa-map-pin'>&#xf276; map-pin</option>
<option {{  $selected == 'fa fa-map-signs' ? 'selected' : '' }} value='fa fa-map-signs'>&#xf277; map-signs</option>
<option {{  $selected == 'fa fa-mars' ? 'selected' : '' }} value='fa fa-mars'>&#xf222; mars</option>
<option {{  $selected == 'fa fa-mars-double' ? 'selected' : '' }} value='fa fa-mars-double'>&#xf227; mars-double</option>
<option {{  $selected == 'fa fa-mars-stroke' ? 'selected' : '' }} value='fa fa-mars-stroke'>&#xf229; mars-stroke</option>
<option {{  $selected == 'fa fa-mars-stroke-h' ? 'selected' : '' }} value='fa fa-mars-stroke-h'>&#xf22b; mars-stroke-h</option>
<option {{  $selected == 'fa fa-mars-stroke-v' ? 'selected' : '' }} value='fa fa-mars-stroke-v'>&#xf22a; mars-stroke-v</option>
<option {{  $selected == 'fa fa-maxcdn' ? 'selected' : '' }} value='fa fa-maxcdn'>&#xf136; maxcdn</option>
<option {{  $selected == 'fa fa-meanpath' ? 'selected' : '' }} value='fa fa-meanpath'>&#xf20c; meanpath</option>
<option {{  $selected == 'fa fa-medium' ? 'selected' : '' }} value='fa fa-medium'>&#xf23a; medium</option>
<option {{  $selected == 'fa fa-medkit' ? 'selected' : '' }} value='fa fa-medkit'>&#xf0fa; medkit</option>
<option {{  $selected == 'fa fa-meetup' ? 'selected' : '' }} value='fa fa-meetup'>&#xf2e0; meetup</option>
<option {{  $selected == 'fa fa-meh-o' ? 'selected' : '' }} value='fa fa-meh-o'>&#xf11a; meh-o</option>
<option {{  $selected == 'fa fa-mercury' ? 'selected' : '' }} value='fa fa-mercury'>&#xf223; mercury</option>
<option {{  $selected == 'fa fa-microchip' ? 'selected' : '' }} value='fa fa-microchip'>&#xf2db; microchip</option>
<option {{  $selected == 'fa fa-microphone' ? 'selected' : '' }} value='fa fa-microphone'>&#xf130; microphone</option>
<option {{  $selected == 'fa fa-microphone-slash' ? 'selected' : '' }} value='fa fa-microphone-slash'>&#xf131; microphone-slash</option>
<option {{  $selected == 'fa fa-minus' ? 'selected' : '' }} value='fa fa-minus'>&#xf068; minus</option>
<option {{  $selected == 'fa fa-minus-circle' ? 'selected' : '' }} value='fa fa-minus-circle'>&#xf056; minus-circle</option>
<option {{  $selected == 'fa fa-minus-square' ? 'selected' : '' }} value='fa fa-minus-square'>&#xf146; minus-square</option>
<option {{  $selected == 'fa fa-minus-square-o' ? 'selected' : '' }} value='fa fa-minus-square-o'>&#xf147; minus-square-o</option>
<option {{  $selected == 'fa fa-mixcloud' ? 'selected' : '' }} value='fa fa-mixcloud'>&#xf289; mixcloud</option>
<option {{  $selected == 'fa fa-mobile' ? 'selected' : '' }} value='fa fa-mobile'>&#xf10b; mobile</option>
<option {{  $selected == 'fa fa-mobile-phone' ? 'selected' : '' }} value='fa fa-mobile-phone'>&#xf10b; mobile-phone</option>
<option {{  $selected == 'fa fa-modx' ? 'selected' : '' }} value='fa fa-modx'>&#xf285; modx</option>
<option {{  $selected == 'fa fa-money' ? 'selected' : '' }} value='fa fa-money'>&#xf0d6; money</option>
<option {{  $selected == 'fa fa-moon-o' ? 'selected' : '' }} value='fa fa-moon-o'>&#xf186; moon-o</option>
<option {{  $selected == 'fa fa-mortar-board' ? 'selected' : '' }} value='fa fa-mortar-board'>&#xf19d; mortar-board</option>
<option {{  $selected == 'fa fa-motorcycle' ? 'selected' : '' }} value='fa fa-motorcycle'>&#xf21c; motorcycle</option>
<option {{  $selected == 'fa fa-mouse-pointer' ? 'selected' : '' }} value='fa fa-mouse-pointer'>&#xf245; mouse-pointer</option>
<option {{  $selected == 'fa fa-music' ? 'selected' : '' }} value='fa fa-music'>&#xf001; music</option>
<option {{  $selected == 'fa fa-navicon' ? 'selected' : '' }} value='fa fa-navicon'>&#xf0c9; navicon</option>
<option {{  $selected == 'fa fa-neuter' ? 'selected' : '' }} value='fa fa-neuter'>&#xf22c; neuter</option>
<option {{  $selected == 'fa fa-newspaper-o' ? 'selected' : '' }} value='fa fa-newspaper-o'>&#xf1ea; newspaper-o</option>
<option {{  $selected == 'fa fa-object-group' ? 'selected' : '' }} value='fa fa-object-group'>&#xf247; object-group</option>
<option {{  $selected == 'fa fa-object-ungroup' ? 'selected' : '' }} value='fa fa-object-ungroup'>&#xf248; object-ungroup</option>
<option {{  $selected == 'fa fa-odnoklassniki' ? 'selected' : '' }} value='fa fa-odnoklassniki'>&#xf263; odnoklassniki</option>
<option {{  $selected == 'fa fa-odnoklassniki-square' ? 'selected' : '' }} value='fa fa-odnoklassniki-square'>&#xf264; odnoklassniki-square</option>
<option {{  $selected == 'fa fa-opencart' ? 'selected' : '' }} value='fa fa-opencart'>&#xf23d; opencart</option>
<option {{  $selected == 'fa fa-openid' ? 'selected' : '' }} value='fa fa-openid'>&#xf19b; openid</option>
<option {{  $selected == 'fa fa-opera' ? 'selected' : '' }} value='fa fa-opera'>&#xf26a; opera</option>
<option {{  $selected == 'fa fa-optin-monster' ? 'selected' : '' }} value='fa fa-optin-monster'>&#xf23c; optin-monster</option>
<option {{  $selected == 'fa fa-outdent' ? 'selected' : '' }} value='fa fa-outdent'>&#xf03b; outdent</option>
<option {{  $selected == 'fa fa-pagelines' ? 'selected' : '' }} value='fa fa-pagelines'>&#xf18c; pagelines</option>
<option {{  $selected == 'fa fa-paint-brush' ? 'selected' : '' }} value='fa fa-paint-brush'>&#xf1fc; paint-brush</option>
<option {{  $selected == 'fa fa-paper-plane' ? 'selected' : '' }} value='fa fa-paper-plane'>&#xf1d8; paper-plane</option>
<option {{  $selected == 'fa fa-paper-plane-o' ? 'selected' : '' }} value='fa fa-paper-plane-o'>&#xf1d9; paper-plane-o</option>
<option {{  $selected == 'fa fa-paperclip' ? 'selected' : '' }} value='fa fa-paperclip'>&#xf0c6; paperclip</option>
<option {{  $selected == 'fa fa-paragraph' ? 'selected' : '' }} value='fa fa-paragraph'>&#xf1dd; paragraph</option>
<option {{  $selected == 'fa fa-paste' ? 'selected' : '' }} value='fa fa-paste'>&#xf0ea; paste</option>
<option {{  $selected == 'fa fa-pause' ? 'selected' : '' }} value='fa fa-pause'>&#xf04c; pause</option>
<option {{  $selected == 'fa fa-pause-circle' ? 'selected' : '' }} value='fa fa-pause-circle'>&#xf28b; pause-circle</option>
<option {{  $selected == 'fa fa-pause-circle-o' ? 'selected' : '' }} value='fa fa-pause-circle-o'>&#xf28c; pause-circle-o</option>
<option {{  $selected == 'fa fa-paw' ? 'selected' : '' }} value='fa fa-paw'>&#xf1b0; paw</option>
<option {{  $selected == 'fa fa-paypal' ? 'selected' : '' }} value='fa fa-paypal'>&#xf1ed; paypal</option>
<option {{  $selected == 'fa fa-pencil' ? 'selected' : '' }} value='fa fa-pencil'>&#xf040; pencil</option>
<option {{  $selected == 'fa fa-pencil-square' ? 'selected' : '' }} value='fa fa-pencil-square'>&#xf14b; pencil-square</option>
<option {{  $selected == 'fa fa-pencil-square-o' ? 'selected' : '' }} value='fa fa-pencil-square-o'>&#xf044; pencil-square-o</option>
<option {{  $selected == 'fa fa-percent' ? 'selected' : '' }} value='fa fa-percent'>&#xf295; percent</option>
<option {{  $selected == 'fa fa-phone' ? 'selected' : '' }} value='fa fa-phone'>&#xf095; phone</option>
<option {{  $selected == 'fa fa-phone-square' ? 'selected' : '' }} value='fa fa-phone-square'>&#xf098; phone-square</option>
<option {{  $selected == 'fa fa-photo' ? 'selected' : '' }} value='fa fa-photo'>&#xf03e; photo</option>
<option {{  $selected == 'fa fa-picture-o' ? 'selected' : '' }} value='fa fa-picture-o'>&#xf03e; picture-o</option>
<option {{  $selected == 'fa fa-pie-chart' ? 'selected' : '' }} value='fa fa-pie-chart'>&#xf200; pie-chart</option>
<option {{  $selected == 'fa fa-pied-piper' ? 'selected' : '' }} value='fa fa-pied-piper'>&#xf2ae; pied-piper</option>
<option {{  $selected == 'fa fa-pied-piper-alt' ? 'selected' : '' }} value='fa fa-pied-piper-alt'>&#xf1a8; pied-piper-alt</option>
<option {{  $selected == 'fa fa-pied-piper-pp' ? 'selected' : '' }} value='fa fa-pied-piper-pp'>&#xf1a7; pied-piper-pp</option>
<option {{  $selected == 'fa fa-pinterest' ? 'selected' : '' }} value='fa fa-pinterest'>&#xf0d2; pinterest</option>
<option {{  $selected == 'fa fa-pinterest-p' ? 'selected' : '' }} value='fa fa-pinterest-p'>&#xf231; pinterest-p</option>
<option {{  $selected == 'fa fa-pinterest-square' ? 'selected' : '' }} value='fa fa-pinterest-square'>&#xf0d3; pinterest-square</option>
<option {{  $selected == 'fa fa-plane' ? 'selected' : '' }} value='fa fa-plane'>&#xf072; plane</option>
<option {{  $selected == 'fa fa-play' ? 'selected' : '' }} value='fa fa-play'>&#xf04b; play</option>
<option {{  $selected == 'fa fa-play-circle' ? 'selected' : '' }} value='fa fa-play-circle'>&#xf144; play-circle</option>
<option {{  $selected == 'fa fa-play-circle-o' ? 'selected' : '' }} value='fa fa-play-circle-o'>&#xf01d; play-circle-o</option>
<option {{  $selected == 'fa fa-plug' ? 'selected' : '' }} value='fa fa-plug'>&#xf1e6; plug</option>
<option {{  $selected == 'fa fa-plus' ? 'selected' : '' }} value='fa fa-plus'>&#xf067; plus</option>
<option {{  $selected == 'fa fa-plus-circle' ? 'selected' : '' }} value='fa fa-plus-circle'>&#xf055; plus-circle</option>
<option {{  $selected == 'fa fa-plus-square' ? 'selected' : '' }} value='fa fa-plus-square'>&#xf0fe; plus-square</option>
<option {{  $selected == 'fa fa-plus-square-o' ? 'selected' : '' }} value='fa fa-plus-square-o'>&#xf196; plus-square-o</option>
<option {{  $selected == 'fa fa-podcast' ? 'selected' : '' }} value='fa fa-podcast'>&#xf2ce; podcast</option>
<option {{  $selected == 'fa fa-power-off' ? 'selected' : '' }} value='fa fa-power-off'>&#xf011; power-off</option>
<option {{  $selected == 'fa fa-print' ? 'selected' : '' }} value='fa fa-print'>&#xf02f; print</option>
<option {{  $selected == 'fa fa-product-hunt' ? 'selected' : '' }} value='fa fa-product-hunt'>&#xf288; product-hunt</option>
<option {{  $selected == 'fa fa-puzzle-piece' ? 'selected' : '' }} value='fa fa-puzzle-piece'>&#xf12e; puzzle-piece</option>
<option {{  $selected == 'fa fa-qq' ? 'selected' : '' }} value='fa fa-qq'>&#xf1d6; qq</option>
<option {{  $selected == 'fa fa-qrcode' ? 'selected' : '' }} value='fa fa-qrcode'>&#xf029; qrcode</option>
<option {{  $selected == 'fa fa-question' ? 'selected' : '' }} value='fa fa-question'>&#xf128; question</option>
<option {{  $selected == 'fa fa-question-circle' ? 'selected' : '' }} value='fa fa-question-circle'>&#xf059; question-circle</option>
<option {{  $selected == 'fa fa-question-circle-o' ? 'selected' : '' }} value='fa fa-question-circle-o'>&#xf29c; question-circle-o</option>
<option {{  $selected == 'fa fa-quora' ? 'selected' : '' }} value='fa fa-quora'>&#xf2c4; quora</option>
<option {{  $selected == 'fa fa-quote-left' ? 'selected' : '' }} value='fa fa-quote-left'>&#xf10d; quote-left</option>
<option {{  $selected == 'fa fa-quote-right' ? 'selected' : '' }} value='fa fa-quote-right'>&#xf10e; quote-right</option>
<option {{  $selected == 'fa fa-ra' ? 'selected' : '' }} value='fa fa-ra'>&#xf1d0; ra</option>
<option {{  $selected == 'fa fa-random' ? 'selected' : '' }} value='fa fa-random'>&#xf074; random</option>
<option {{  $selected == 'fa fa-ravelry' ? 'selected' : '' }} value='fa fa-ravelry'>&#xf2d9; ravelry</option>
<option {{  $selected == 'fa fa-rebel' ? 'selected' : '' }} value='fa fa-rebel'>&#xf1d0; rebel</option>
<option {{  $selected == 'fa fa-recycle' ? 'selected' : '' }} value='fa fa-recycle'>&#xf1b8; recycle</option>
<option {{  $selected == 'fa fa-reddit' ? 'selected' : '' }} value='fa fa-reddit'>&#xf1a1; reddit</option>
<option {{  $selected == 'fa fa-reddit-alien' ? 'selected' : '' }} value='fa fa-reddit-alien'>&#xf281; reddit-alien</option>
<option {{  $selected == 'fa fa-reddit-square' ? 'selected' : '' }} value='fa fa-reddit-square'>&#xf1a2; reddit-square</option>
<option {{  $selected == 'fa fa-refresh' ? 'selected' : '' }} value='fa fa-refresh'>&#xf021; refresh</option>
<option {{  $selected == 'fa fa-registered' ? 'selected' : '' }} value='fa fa-registered'>&#xf25d; registered</option>
<option {{  $selected == 'fa fa-remove' ? 'selected' : '' }} value='fa fa-remove'>&#xf00d; remove</option>
<option {{  $selected == 'fa fa-renren' ? 'selected' : '' }} value='fa fa-renren'>&#xf18b; renren</option>
<option {{  $selected == 'fa fa-reorder' ? 'selected' : '' }} value='fa fa-reorder'>&#xf0c9; reorder</option>
<option {{  $selected == 'fa fa-repeat' ? 'selected' : '' }} value='fa fa-repeat'>&#xf01e; repeat</option>
<option {{  $selected == 'fa fa-reply' ? 'selected' : '' }} value='fa fa-reply'>&#xf112; reply</option>
<option {{  $selected == 'fa fa-reply-all' ? 'selected' : '' }} value='fa fa-reply-all'>&#xf122; reply-all</option>
<option {{  $selected == 'fa fa-resistance' ? 'selected' : '' }} value='fa fa-resistance'>&#xf1d0; resistance</option>
<option {{  $selected == 'fa fa-retweet' ? 'selected' : '' }} value='fa fa-retweet'>&#xf079; retweet</option>
<option {{  $selected == 'fa fa-rmb' ? 'selected' : '' }} value='fa fa-rmb'>&#xf157; rmb</option>
<option {{  $selected == 'fa fa-road' ? 'selected' : '' }} value='fa fa-road'>&#xf018; road</option>
<option {{  $selected == 'fa fa-rocket' ? 'selected' : '' }} value='fa fa-rocket'>&#xf135; rocket</option>
<option {{  $selected == 'fa fa-rotate-left' ? 'selected' : '' }} value='fa fa-rotate-left'>&#xf0e2; rotate-left</option>
<option {{  $selected == 'fa fa-rotate-right' ? 'selected' : '' }} value='fa fa-rotate-right'>&#xf01e; rotate-right</option>
<option {{  $selected == 'fa fa-rouble' ? 'selected' : '' }} value='fa fa-rouble'>&#xf158; rouble</option>
<option {{  $selected == 'fa fa-rss' ? 'selected' : '' }} value='fa fa-rss'>&#xf09e; rss</option>
<option {{  $selected == 'fa fa-rss-square' ? 'selected' : '' }} value='fa fa-rss-square'>&#xf143; rss-square</option>
<option {{  $selected == 'fa fa-rub' ? 'selected' : '' }} value='fa fa-rub'>&#xf158; rub</option>
<option {{  $selected == 'fa fa-ruble' ? 'selected' : '' }} value='fa fa-ruble'>&#xf158; ruble</option>
<option {{  $selected == 'fa fa-rupee' ? 'selected' : '' }} value='fa fa-rupee'>&#xf156; rupee</option>
<option {{  $selected == 'fa fa-s15' ? 'selected' : '' }} value='fa fa-s15'>&#xf2cd; s15</option>
<option {{  $selected == 'fa fa-safari' ? 'selected' : '' }} value='fa fa-safari'>&#xf267; safari</option>
<option {{  $selected == 'fa fa-save' ? 'selected' : '' }} value='fa fa-save'>&#xf0c7; save</option>
<option {{  $selected == 'fa fa-scissors' ? 'selected' : '' }} value='fa fa-scissors'>&#xf0c4; scissors</option>
<option {{  $selected == 'fa fa-scribd' ? 'selected' : '' }} value='fa fa-scribd'>&#xf28a; scribd</option>
<option {{  $selected == 'fa fa-search' ? 'selected' : '' }} value='fa fa-search'>&#xf002; search</option>
<option {{  $selected == 'fa fa-search-minus' ? 'selected' : '' }} value='fa fa-search-minus'>&#xf010; search-minus</option>
<option {{  $selected == 'fa fa-search-plus' ? 'selected' : '' }} value='fa fa-search-plus'>&#xf00e; search-plus</option>
<option {{  $selected == 'fa fa-sellsy' ? 'selected' : '' }} value='fa fa-sellsy'>&#xf213; sellsy</option>
<option {{  $selected == 'fa fa-send' ? 'selected' : '' }} value='fa fa-send'>&#xf1d8; send</option>
<option {{  $selected == 'fa fa-send-o' ? 'selected' : '' }} value='fa fa-send-o'>&#xf1d9; send-o</option>
<option {{  $selected == 'fa fa-server' ? 'selected' : '' }} value='fa fa-server'>&#xf233; server</option>
<option {{  $selected == 'fa fa-share' ? 'selected' : '' }} value='fa fa-share'>&#xf064; share</option>
<option {{  $selected == 'fa fa-share-alt' ? 'selected' : '' }} value='fa fa-share-alt'>&#xf1e0; share-alt</option>
<option {{  $selected == 'fa fa-share-alt-square' ? 'selected' : '' }} value='fa fa-share-alt-square'>&#xf1e1; share-alt-square</option>
<option {{  $selected == 'fa fa-share-square' ? 'selected' : '' }} value='fa fa-share-square'>&#xf14d; share-square</option>
<option {{  $selected == 'fa fa-share-square-o' ? 'selected' : '' }} value='fa fa-share-square-o'>&#xf045; share-square-o</option>
<option {{  $selected == 'fa fa-shekel' ? 'selected' : '' }} value='fa fa-shekel'>&#xf20b; shekel</option>
<option {{  $selected == 'fa fa-sheqel' ? 'selected' : '' }} value='fa fa-sheqel'>&#xf20b; sheqel</option>
<option {{  $selected == 'fa fa-shield' ? 'selected' : '' }} value='fa fa-shield'>&#xf132; shield</option>
<option {{  $selected == 'fa fa-ship' ? 'selected' : '' }} value='fa fa-ship'>&#xf21a; ship</option>
<option {{  $selected == 'fa fa-shirtsinbulk' ? 'selected' : '' }} value='fa fa-shirtsinbulk'>&#xf214; shirtsinbulk</option>
<option {{  $selected == 'fa fa-shopping-bag' ? 'selected' : '' }} value='fa fa-shopping-bag'>&#xf290; shopping-bag</option>
<option {{  $selected == 'fa fa-shopping-basket' ? 'selected' : '' }} value='fa fa-shopping-basket'>&#xf291; shopping-basket</option>
<option {{  $selected == 'fa fa-shopping-cart' ? 'selected' : '' }} value='fa fa-shopping-cart'>&#xf07a; shopping-cart</option>
<option {{  $selected == 'fa fa-shower' ? 'selected' : '' }} value='fa fa-shower'>&#xf2cc; shower</option>
<option {{  $selected == 'fa fa-sign-in' ? 'selected' : '' }} value='fa fa-sign-in'>&#xf090; sign-in</option>
<option {{  $selected == 'fa fa-sign-language' ? 'selected' : '' }} value='fa fa-sign-language'>&#xf2a7; sign-language</option>
<option {{  $selected == 'fa fa-sign-out' ? 'selected' : '' }} value='fa fa-sign-out'>&#xf08b; sign-out</option>
<option {{  $selected == 'fa fa-signal' ? 'selected' : '' }} value='fa fa-signal'>&#xf012; signal</option>
<option {{  $selected == 'fa fa-signing' ? 'selected' : '' }} value='fa fa-signing'>&#xf2a7; signing</option>
<option {{  $selected == 'fa fa-simplybuilt' ? 'selected' : '' }} value='fa fa-simplybuilt'>&#xf215; simplybuilt</option>
<option {{  $selected == 'fa fa-sitemap' ? 'selected' : '' }} value='fa fa-sitemap'>&#xf0e8; sitemap</option>
<option {{  $selected == 'fa fa-skyatlas' ? 'selected' : '' }} value='fa fa-skyatlas'>&#xf216; skyatlas</option>
<option {{  $selected == 'fa fa-skype' ? 'selected' : '' }} value='fa fa-skype'>&#xf17e; skype</option>
<option {{  $selected == 'fa fa-slack' ? 'selected' : '' }} value='fa fa-slack'>&#xf198; slack</option>
<option {{  $selected == 'fa fa-sliders' ? 'selected' : '' }} value='fa fa-sliders'>&#xf1de; sliders</option>
<option {{  $selected == 'fa fa-slideshare' ? 'selected' : '' }} value='fa fa-slideshare'>&#xf1e7; slideshare</option>
<option {{  $selected == 'fa fa-smile-o' ? 'selected' : '' }} value='fa fa-smile-o'>&#xf118; smile-o</option>
<option {{  $selected == 'fa fa-snapchat' ? 'selected' : '' }} value='fa fa-snapchat'>&#xf2ab; snapchat</option>
<option {{  $selected == 'fa fa-snapchat-ghost' ? 'selected' : '' }} value='fa fa-snapchat-ghost'>&#xf2ac; snapchat-ghost</option>
<option {{  $selected == 'fa fa-snapchat-square' ? 'selected' : '' }} value='fa fa-snapchat-square'>&#xf2ad; snapchat-square</option>
<option {{  $selected == 'fa fa-snowflake-o' ? 'selected' : '' }} value='fa fa-snowflake-o'>&#xf2dc; snowflake-o</option>
<option {{  $selected == 'fa fa-soccer-ball-o' ? 'selected' : '' }} value='fa fa-soccer-ball-o'>&#xf1e3; soccer-ball-o</option>
<option {{  $selected == 'fa fa-sort' ? 'selected' : '' }} value='fa fa-sort'>&#xf0dc; sort</option>
<option {{  $selected == 'fa fa-sort-alpha-asc' ? 'selected' : '' }} value='fa fa-sort-alpha-asc'>&#xf15d; sort-alpha-asc</option>
<option {{  $selected == 'fa fa-sort-alpha-desc' ? 'selected' : '' }} value='fa fa-sort-alpha-desc'>&#xf15e; sort-alpha-desc</option>
<option {{  $selected == 'fa fa-sort-amount-asc' ? 'selected' : '' }} value='fa fa-sort-amount-asc'>&#xf160; sort-amount-asc</option>
<option {{  $selected == 'fa fa-sort-amount-desc' ? 'selected' : '' }} value='fa fa-sort-amount-desc'>&#xf161; sort-amount-desc</option>
<option {{  $selected == 'fa fa-sort-asc' ? 'selected' : '' }} value='fa fa-sort-asc'>&#xf0de; sort-asc</option>
<option {{  $selected == 'fa fa-sort-desc' ? 'selected' : '' }} value='fa fa-sort-desc'>&#xf0dd; sort-desc</option>
<option {{  $selected == 'fa fa-sort-down' ? 'selected' : '' }} value='fa fa-sort-down'>&#xf0dd; sort-down</option>
<option {{  $selected == 'fa fa-sort-numeric-asc' ? 'selected' : '' }} value='fa fa-sort-numeric-asc'>&#xf162; sort-numeric-asc</option>
<option {{  $selected == 'fa fa-sort-numeric-desc' ? 'selected' : '' }} value='fa fa-sort-numeric-desc'>&#xf163; sort-numeric-desc</option>
<option {{  $selected == 'fa fa-sort-up' ? 'selected' : '' }} value='fa fa-sort-up'>&#xf0de; sort-up</option>
<option {{  $selected == 'fa fa-soundcloud' ? 'selected' : '' }} value='fa fa-soundcloud'>&#xf1be; soundcloud</option>
<option {{  $selected == 'fa fa-space-shuttle' ? 'selected' : '' }} value='fa fa-space-shuttle'>&#xf197; space-shuttle</option>
<option {{  $selected == 'fa fa-spinner' ? 'selected' : '' }} value='fa fa-spinner'>&#xf110; spinner</option>
<option {{  $selected == 'fa fa-spoon' ? 'selected' : '' }} value='fa fa-spoon'>&#xf1b1; spoon</option>
<option {{  $selected == 'fa fa-spotify' ? 'selected' : '' }} value='fa fa-spotify'>&#xf1bc; spotify</option>
<option {{  $selected == 'fa fa-square' ? 'selected' : '' }} value='fa fa-square'>&#xf0c8; square</option>
<option {{  $selected == 'fa fa-square-o' ? 'selected' : '' }} value='fa fa-square-o'>&#xf096; square-o</option>
<option {{  $selected == 'fa fa-stack-exchange' ? 'selected' : '' }} value='fa fa-stack-exchange'>&#xf18d; stack-exchange</option>
<option {{  $selected == 'fa fa-stack-overflow' ? 'selected' : '' }} value='fa fa-stack-overflow'>&#xf16c; stack-overflow</option>
<option {{  $selected == 'fa fa-star' ? 'selected' : '' }} value='fa fa-star'>&#xf005; star</option>
<option {{  $selected == 'fa fa-star-half' ? 'selected' : '' }} value='fa fa-star-half'>&#xf089; star-half</option>
<option {{  $selected == 'fa fa-star-half-empty' ? 'selected' : '' }} value='fa fa-star-half-empty'>&#xf123; star-half-empty</option>
<option {{  $selected == 'fa fa-star-half-full' ? 'selected' : '' }} value='fa fa-star-half-full'>&#xf123; star-half-full</option>
<option {{  $selected == 'fa fa-star-half-o' ? 'selected' : '' }} value='fa fa-star-half-o'>&#xf123; star-half-o</option>
<option {{  $selected == 'fa fa-star-o' ? 'selected' : '' }} value='fa fa-star-o'>&#xf006; star-o</option>
<option {{  $selected == 'fa fa-steam' ? 'selected' : '' }} value='fa fa-steam'>&#xf1b6; steam</option>
<option {{  $selected == 'fa fa-steam-square' ? 'selected' : '' }} value='fa fa-steam-square'>&#xf1b7; steam-square</option>
<option {{  $selected == 'fa fa-step-backward' ? 'selected' : '' }} value='fa fa-step-backward'>&#xf048; step-backward</option>
<option {{  $selected == 'fa fa-step-forward' ? 'selected' : '' }} value='fa fa-step-forward'>&#xf051; step-forward</option>
<option {{  $selected == 'fa fa-stethoscope' ? 'selected' : '' }} value='fa fa-stethoscope'>&#xf0f1; stethoscope</option>
<option {{  $selected == 'fa fa-sticky-note' ? 'selected' : '' }} value='fa fa-sticky-note'>&#xf249; sticky-note</option>
<option {{  $selected == 'fa fa-sticky-note-o' ? 'selected' : '' }} value='fa fa-sticky-note-o'>&#xf24a; sticky-note-o</option>
<option {{  $selected == 'fa fa-stop' ? 'selected' : '' }} value='fa fa-stop'>&#xf04d; stop</option>
<option {{  $selected == 'fa fa-stop-circle' ? 'selected' : '' }} value='fa fa-stop-circle'>&#xf28d; stop-circle</option>
<option {{  $selected == 'fa fa-stop-circle-o' ? 'selected' : '' }} value='fa fa-stop-circle-o'>&#xf28e; stop-circle-o</option>
<option {{  $selected == 'fa fa-street-view' ? 'selected' : '' }} value='fa fa-street-view'>&#xf21d; street-view</option>
<option {{  $selected == 'fa fa-strikethrough' ? 'selected' : '' }} value='fa fa-strikethrough'>&#xf0cc; strikethrough</option>
<option {{  $selected == 'fa fa-stumbleupon' ? 'selected' : '' }} value='fa fa-stumbleupon'>&#xf1a4; stumbleupon</option>
<option {{  $selected == 'fa fa-stumbleupon-circle' ? 'selected' : '' }} value='fa fa-stumbleupon-circle'>&#xf1a3; stumbleupon-circle</option>
<option {{  $selected == 'fa fa-subscript' ? 'selected' : '' }} value='fa fa-subscript'>&#xf12c; subscript</option>
<option {{  $selected == 'fa fa-subway' ? 'selected' : '' }} value='fa fa-subway'>&#xf239; subway</option>
<option {{  $selected == 'fa fa-suitcase' ? 'selected' : '' }} value='fa fa-suitcase'>&#xf0f2; suitcase</option>
<option {{  $selected == 'fa fa-sun-o' ? 'selected' : '' }} value='fa fa-sun-o'>&#xf185; sun-o</option>
<option {{  $selected == 'fa fa-superpowers' ? 'selected' : '' }} value='fa fa-superpowers'>&#xf2dd; superpowers</option>
<option {{  $selected == 'fa fa-superscript' ? 'selected' : '' }} value='fa fa-superscript'>&#xf12b; superscript</option>
<option {{  $selected == 'fa fa-support' ? 'selected' : '' }} value='fa fa-support'>&#xf1cd; support</option>
<option {{  $selected == 'fa fa-table' ? 'selected' : '' }} value='fa fa-table'>&#xf0ce; table</option>
<option {{  $selected == 'fa fa-tablet' ? 'selected' : '' }} value='fa fa-tablet'>&#xf10a; tablet</option>
<option {{  $selected == 'fa fa-tachometer' ? 'selected' : '' }} value='fa fa-tachometer'>&#xf0e4; tachometer</option>
<option {{  $selected == 'fa fa-tag' ? 'selected' : '' }} value='fa fa-tag'>&#xf02b; tag</option>
<option {{  $selected == 'fa fa-tags' ? 'selected' : '' }} value='fa fa-tags'>&#xf02c; tags</option>
<option {{  $selected == 'fa fa-tasks' ? 'selected' : '' }} value='fa fa-tasks'>&#xf0ae; tasks</option>
<option {{  $selected == 'fa fa-taxi' ? 'selected' : '' }} value='fa fa-taxi'>&#xf1ba; taxi</option>
<option {{  $selected == 'fa fa-telegram' ? 'selected' : '' }} value='fa fa-telegram'>&#xf2c6; telegram</option>
<option {{  $selected == 'fa fa-television' ? 'selected' : '' }} value='fa fa-television'>&#xf26c; television</option>
<option {{  $selected == 'fa fa-tencent-weibo' ? 'selected' : '' }} value='fa fa-tencent-weibo'>&#xf1d5; tencent-weibo</option>
<option {{  $selected == 'fa fa-terminal' ? 'selected' : '' }} value='fa fa-terminal'>&#xf120; terminal</option>
<option {{  $selected == 'fa fa-text-height' ? 'selected' : '' }} value='fa fa-text-height'>&#xf034; text-height</option>
<option {{  $selected == 'fa fa-text-width' ? 'selected' : '' }} value='fa fa-text-width'>&#xf035; text-width</option>
<option {{  $selected == 'fa fa-th' ? 'selected' : '' }} value='fa fa-th'>&#xf00a; th</option>
<option {{  $selected == 'fa fa-th-large' ? 'selected' : '' }} value='fa fa-th-large'>&#xf009; th-large</option>
<option {{  $selected == 'fa fa-th-list' ? 'selected' : '' }} value='fa fa-th-list'>&#xf00b; th-list</option>
<option {{  $selected == 'fa fa-themeisle' ? 'selected' : '' }} value='fa fa-themeisle'>&#xf2b2; themeisle</option>
<option {{  $selected == 'fa fa-thermometer' ? 'selected' : '' }} value='fa fa-thermometer'>&#xf2c7; thermometer</option>
<option {{  $selected == 'fa fa-thermometer-0' ? 'selected' : '' }} value='fa fa-thermometer-0'>&#xf2cb; thermometer-0</option>
<option {{  $selected == 'fa fa-thermometer-1' ? 'selected' : '' }} value='fa fa-thermometer-1'>&#xf2ca; thermometer-1</option>
<option {{  $selected == 'fa fa-thermometer-2' ? 'selected' : '' }} value='fa fa-thermometer-2'>&#xf2c9; thermometer-2</option>
<option {{  $selected == 'fa fa-thermometer-3' ? 'selected' : '' }} value='fa fa-thermometer-3'>&#xf2c8; thermometer-3</option>
<option {{  $selected == 'fa fa-thermometer-4' ? 'selected' : '' }} value='fa fa-thermometer-4'>&#xf2c7; thermometer-4</option>
<option {{  $selected == 'fa fa-thermometer-empty' ? 'selected' : '' }} value='fa fa-thermometer-empty'>&#xf2cb; thermometer-empty</option>
<option {{  $selected == 'fa fa-thermometer-full' ? 'selected' : '' }} value='fa fa-thermometer-full'>&#xf2c7; thermometer-full</option>
<option {{  $selected == 'fa fa-thermometer-half' ? 'selected' : '' }} value='fa fa-thermometer-half'>&#xf2c9; thermometer-half</option>
<option {{  $selected == 'fa fa-thermometer-quarter' ? 'selected' : '' }} value='fa fa-thermometer-quarter'>&#xf2ca; thermometer-quarter</option>
<option {{  $selected == 'fa fa-thermometer-three-quarters' ? 'selected' : '' }} value='fa fa-thermometer-three-quarters'>&#xf2c8; thermometer-three-quarters</option>
<option {{  $selected == 'fa fa-thumb-tack' ? 'selected' : '' }} value='fa fa-thumb-tack'>&#xf08d; thumb-tack</option>
<option {{  $selected == 'fa fa-thumbs-down' ? 'selected' : '' }} value='fa fa-thumbs-down'>&#xf165; thumbs-down</option>
<option {{  $selected == 'fa fa-thumbs-o-down' ? 'selected' : '' }} value='fa fa-thumbs-o-down'>&#xf088; thumbs-o-down</option>
<option {{  $selected == 'fa fa-thumbs-o-up' ? 'selected' : '' }} value='fa fa-thumbs-o-up'>&#xf087; thumbs-o-up</option>
<option {{  $selected == 'fa fa-thumbs-up' ? 'selected' : '' }} value='fa fa-thumbs-up'>&#xf164; thumbs-up</option>
<option {{  $selected == 'fa fa-ticket' ? 'selected' : '' }} value='fa fa-ticket'>&#xf145; ticket</option>
<option {{  $selected == 'fa fa-times' ? 'selected' : '' }} value='fa fa-times'>&#xf00d; times</option>
<option {{  $selected == 'fa fa-times-circle' ? 'selected' : '' }} value='fa fa-times-circle'>&#xf057; times-circle</option>
<option {{  $selected == 'fa fa-times-circle-o' ? 'selected' : '' }} value='fa fa-times-circle-o'>&#xf05c; times-circle-o</option>
<option {{  $selected == 'fa fa-times-rectangle' ? 'selected' : '' }} value='fa fa-times-rectangle'>&#xf2d3; times-rectangle</option>
<option {{  $selected == 'fa fa-times-rectangle-o' ? 'selected' : '' }} value='fa fa-times-rectangle-o'>&#xf2d4; times-rectangle-o</option>
<option {{  $selected == 'fa fa-tint' ? 'selected' : '' }} value='fa fa-tint'>&#xf043; tint</option>
<option {{  $selected == 'fa fa-toggle-down' ? 'selected' : '' }} value='fa fa-toggle-down'>&#xf150; toggle-down</option>
<option {{  $selected == 'fa fa-toggle-left' ? 'selected' : '' }} value='fa fa-toggle-left'>&#xf191; toggle-left</option>
<option {{  $selected == 'fa fa-toggle-off' ? 'selected' : '' }} value='fa fa-toggle-off'>&#xf204; toggle-off</option>
<option {{  $selected == 'fa fa-toggle-on' ? 'selected' : '' }} value='fa fa-toggle-on'>&#xf205; toggle-on</option>
<option {{  $selected == 'fa fa-toggle-right' ? 'selected' : '' }} value='fa fa-toggle-right'>&#xf152; toggle-right</option>
<option {{  $selected == 'fa fa-toggle-up' ? 'selected' : '' }} value='fa fa-toggle-up'>&#xf151; toggle-up</option>
<option {{  $selected == 'fa fa-trademark' ? 'selected' : '' }} value='fa fa-trademark'>&#xf25c; trademark</option>
<option {{  $selected == 'fa fa-train' ? 'selected' : '' }} value='fa fa-train'>&#xf238; train</option>
<option {{  $selected == 'fa fa-transgender' ? 'selected' : '' }} value='fa fa-transgender'>&#xf224; transgender</option>
<option {{  $selected == 'fa fa-transgender-alt' ? 'selected' : '' }} value='fa fa-transgender-alt'>&#xf225; transgender-alt</option>
<option {{  $selected == 'fa fa-trash' ? 'selected' : '' }} value='fa fa-trash'>&#xf1f8; trash</option>
<option {{  $selected == 'fa fa-trash-o' ? 'selected' : '' }} value='fa fa-trash-o'>&#xf014; trash-o</option>
<option {{  $selected == 'fa fa-tree' ? 'selected' : '' }} value='fa fa-tree'>&#xf1bb; tree</option>
<option {{  $selected == 'fa fa-trello' ? 'selected' : '' }} value='fa fa-trello'>&#xf181; trello</option>
<option {{  $selected == 'fa fa-tripadvisor' ? 'selected' : '' }} value='fa fa-tripadvisor'>&#xf262; tripadvisor</option>
<option {{  $selected == 'fa fa-trophy' ? 'selected' : '' }} value='fa fa-trophy'>&#xf091; trophy</option>
<option {{  $selected == 'fa fa-truck' ? 'selected' : '' }} value='fa fa-truck'>&#xf0d1; truck</option>
<option {{  $selected == 'fa fa-try' ? 'selected' : '' }} value='fa fa-try'>&#xf195; try</option>
<option {{  $selected == 'fa fa-tty' ? 'selected' : '' }} value='fa fa-tty'>&#xf1e4; tty</option>
<option {{  $selected == 'fa fa-tumblr' ? 'selected' : '' }} value='fa fa-tumblr'>&#xf173; tumblr</option>
<option {{  $selected == 'fa fa-tumblr-square' ? 'selected' : '' }} value='fa fa-tumblr-square'>&#xf174; tumblr-square</option>
<option {{  $selected == 'fa fa-turkish-lira' ? 'selected' : '' }} value='fa fa-turkish-lira'>&#xf195; turkish-lira</option>
<option {{  $selected == 'fa fa-tv' ? 'selected' : '' }} value='fa fa-tv'>&#xf26c; tv</option>
<option {{  $selected == 'fa fa-twitch' ? 'selected' : '' }} value='fa fa-twitch'>&#xf1e8; twitch</option>
<option {{  $selected == 'fa fa-twitter' ? 'selected' : '' }} value='fa fa-twitter'>&#xf099; twitter</option>
<option {{  $selected == 'fa fa-twitter-square' ? 'selected' : '' }} value='fa fa-twitter-square'>&#xf081; twitter-square</option>
<option {{  $selected == 'fa fa-umbrella' ? 'selected' : '' }} value='fa fa-umbrella'>&#xf0e9; umbrella</option>
<option {{  $selected == 'fa fa-underline' ? 'selected' : '' }} value='fa fa-underline'>&#xf0cd; underline</option>
<option {{  $selected == 'fa fa-undo' ? 'selected' : '' }} value='fa fa-undo'>&#xf0e2; undo</option>
<option {{  $selected == 'fa fa-universal-access' ? 'selected' : '' }} value='fa fa-universal-access'>&#xf29a; universal-access</option>
<option {{  $selected == 'fa fa-university' ? 'selected' : '' }} value='fa fa-university'>&#xf19c; university</option>
<option {{  $selected == 'fa fa-unlink' ? 'selected' : '' }} value='fa fa-unlink'>&#xf127; unlink</option>
<option {{  $selected == 'fa fa-unlock' ? 'selected' : '' }} value='fa fa-unlock'>&#xf09c; unlock</option>
<option {{  $selected == 'fa fa-unlock-alt' ? 'selected' : '' }} value='fa fa-unlock-alt'>&#xf13e; unlock-alt</option>
<option {{  $selected == 'fa fa-unsorted' ? 'selected' : '' }} value='fa fa-unsorted'>&#xf0dc; unsorted</option>
<option {{  $selected == 'fa fa-upload' ? 'selected' : '' }} value='fa fa-upload'>&#xf093; upload</option>
<option {{  $selected == 'fa fa-usb' ? 'selected' : '' }} value='fa fa-usb'>&#xf287; usb</option>
<option {{  $selected == 'fa fa-usd' ? 'selected' : '' }} value='fa fa-usd'>&#xf155; usd</option>
<option {{  $selected == 'fa fa-user' ? 'selected' : '' }} value='fa fa-user'>&#xf007; user</option>
<option {{  $selected == 'fa fa-user-circle' ? 'selected' : '' }} value='fa fa-user-circle'>&#xf2bd; user-circle</option>
<option {{  $selected == 'fa fa-user-circle-o' ? 'selected' : '' }} value='fa fa-user-circle-o'>&#xf2be; user-circle-o</option>
<option {{  $selected == 'fa fa-user-md' ? 'selected' : '' }} value='fa fa-user-md'>&#xf0f0; user-md</option>
<option {{  $selected == 'fa fa-user-o' ? 'selected' : '' }} value='fa fa-user-o'>&#xf2c0; user-o</option>
<option {{  $selected == 'fa fa-user-plus' ? 'selected' : '' }} value='fa fa-user-plus'>&#xf234; user-plus</option>
<option {{  $selected == 'fa fa-user-secret' ? 'selected' : '' }} value='fa fa-user-secret'>&#xf21b; user-secret</option>
<option {{  $selected == 'fa fa-user-times' ? 'selected' : '' }} value='fa fa-user-times'>&#xf235; user-times</option>
<option {{  $selected == 'fa fa-users' ? 'selected' : '' }} value='fa fa-users'>&#xf0c0; users</option>
<option {{  $selected == 'fa fa-vcard' ? 'selected' : '' }} value='fa fa-vcard'>&#xf2bb; vcard</option>
<option {{  $selected == 'fa fa-vcard-o' ? 'selected' : '' }} value='fa fa-vcard-o'>&#xf2bc; vcard-o</option>
<option {{  $selected == 'fa fa-venus' ? 'selected' : '' }} value='fa fa-venus'>&#xf221; venus</option>
<option {{  $selected == 'fa fa-venus-double' ? 'selected' : '' }} value='fa fa-venus-double'>&#xf226; venus-double</option>
<option {{  $selected == 'fa fa-venus-mars' ? 'selected' : '' }} value='fa fa-venus-mars'>&#xf228; venus-mars</option>
<option {{  $selected == 'fa fa-viacoin' ? 'selected' : '' }} value='fa fa-viacoin'>&#xf237; viacoin</option>
<option {{  $selected == 'fa fa-viadeo' ? 'selected' : '' }} value='fa fa-viadeo'>&#xf2a9; viadeo</option>
<option {{  $selected == 'fa fa-viadeo-square' ? 'selected' : '' }} value='fa fa-viadeo-square'>&#xf2aa; viadeo-square</option>
<option {{  $selected == 'fa fa-video-camera' ? 'selected' : '' }} value='fa fa-video-camera'>&#xf03d; video-camera</option>
<option {{  $selected == 'fa fa-vimeo' ? 'selected' : '' }} value='fa fa-vimeo'>&#xf27d; vimeo</option>
<option {{  $selected == 'fa fa-vimeo-square' ? 'selected' : '' }} value='fa fa-vimeo-square'>&#xf194; vimeo-square</option>
<option {{  $selected == 'fa fa-vine' ? 'selected' : '' }} value='fa fa-vine'>&#xf1ca; vine</option>
<option {{  $selected == 'fa fa-vk' ? 'selected' : '' }} value='fa fa-vk'>&#xf189; vk</option>
<option {{  $selected == 'fa fa-volume-control-phone' ? 'selected' : '' }} value='fa fa-volume-control-phone'>&#xf2a0; volume-control-phone</option>
<option {{  $selected == 'fa fa-volume-down' ? 'selected' : '' }} value='fa fa-volume-down'>&#xf027; volume-down</option>
<option {{  $selected == 'fa fa-volume-off' ? 'selected' : '' }} value='fa fa-volume-off'>&#xf026; volume-off</option>
<option {{  $selected == 'fa fa-volume-up' ? 'selected' : '' }} value='fa fa-volume-up'>&#xf028; volume-up</option>
<option {{  $selected == 'fa fa-warning' ? 'selected' : '' }} value='fa fa-warning'>&#xf071; warning</option>
<option {{  $selected == 'fa fa-wechat' ? 'selected' : '' }} value='fa fa-wechat'>&#xf1d7; wechat</option>
<option {{  $selected == 'fa fa-weibo' ? 'selected' : '' }} value='fa fa-weibo'>&#xf18a; weibo</option>
<option {{  $selected == 'fa fa-weixin' ? 'selected' : '' }} value='fa fa-weixin'>&#xf1d7; weixin</option>
<option {{  $selected == 'fa fa-whatsapp' ? 'selected' : '' }} value='fa fa-whatsapp'>&#xf232; whatsapp</option>
<option {{  $selected == 'fa fa-wheelchair' ? 'selected' : '' }} value='fa fa-wheelchair'>&#xf193; wheelchair</option>
<option {{  $selected == 'fa fa-wheelchair-alt' ? 'selected' : '' }} value='fa fa-wheelchair-alt'>&#xf29b; wheelchair-alt</option>
<option {{  $selected == 'fa fa-wifi' ? 'selected' : '' }} value='fa fa-wifi'>&#xf1eb; wifi</option>
<option {{  $selected == 'fa fa-wikipedia-w' ? 'selected' : '' }} value='fa fa-wikipedia-w'>&#xf266; wikipedia-w</option>
<option {{  $selected == 'fa fa-window-close' ? 'selected' : '' }} value='fa fa-window-close'>&#xf2d3; window-close</option>
<option {{  $selected == 'fa fa-window-close-o' ? 'selected' : '' }} value='fa fa-window-close-o'>&#xf2d4; window-close-o</option>
<option {{  $selected == 'fa fa-window-maximize' ? 'selected' : '' }} value='fa fa-window-maximize'>&#xf2d0; window-maximize</option>
<option {{  $selected == 'fa fa-window-minimize' ? 'selected' : '' }} value='fa fa-window-minimize'>&#xf2d1; window-minimize</option>
<option {{  $selected == 'fa fa-window-restore' ? 'selected' : '' }} value='fa fa-window-restore'>&#xf2d2; window-restore</option>
<option {{  $selected == 'fa fa-windows' ? 'selected' : '' }} value='fa fa-windows'>&#xf17a; windows</option>
<option {{  $selected == 'fa fa-won' ? 'selected' : '' }} value='fa fa-won'>&#xf159; won</option>
<option {{  $selected == 'fa fa-wordpress' ? 'selected' : '' }} value='fa fa-wordpress'>&#xf19a; wordpress</option>
<option {{  $selected == 'fa fa-wpbeginner' ? 'selected' : '' }} value='fa fa-wpbeginner'>&#xf297; wpbeginner</option>
<option {{  $selected == 'fa fa-wpexplorer' ? 'selected' : '' }} value='fa fa-wpexplorer'>&#xf2de; wpexplorer</option>
<option {{  $selected == 'fa fa-wpforms' ? 'selected' : '' }} value='fa fa-wpforms'>&#xf298; wpforms</option>
<option {{  $selected == 'fa fa-wrench' ? 'selected' : '' }} value='fa fa-wrench'>&#xf0ad; wrench</option>
<option {{  $selected == 'fa fa-xing' ? 'selected' : '' }} value='fa fa-xing'>&#xf168; xing</option>
<option {{  $selected == 'fa fa-xing-square' ? 'selected' : '' }} value='fa fa-xing-square'>&#xf169; xing-square</option>
<option {{  $selected == 'fa fa-y-combinator' ? 'selected' : '' }} value='fa fa-y-combinator'>&#xf23b; y-combinator</option>
<option {{  $selected == 'fa fa-y-combinator-square' ? 'selected' : '' }} value='fa fa-y-combinator-square'>&#xf1d4; y-combinator-square</option>
<option {{  $selected == 'fa fa-yahoo' ? 'selected' : '' }} value='fa fa-yahoo'>&#xf19e; yahoo</option>
<option {{  $selected == 'fa fa-yc' ? 'selected' : '' }} value='fa fa-yc'>&#xf23b; yc</option>
<option {{  $selected == 'fa fa-yc-square' ? 'selected' : '' }} value='fa fa-yc-square'>&#xf1d4; yc-square</option>
<option {{  $selected == 'fa fa-yelp' ? 'selected' : '' }} value='fa fa-yelp'>&#xf1e9; yelp</option>
<option {{  $selected == 'fa fa-yen' ? 'selected' : '' }} value='fa fa-yen'>&#xf157; yen</option>
<option {{  $selected == 'fa fa-yoast' ? 'selected' : '' }} value='fa fa-yoast'>&#xf2b1; yoast</option>
<option {{  $selected == 'fa fa-youtube' ? 'selected' : '' }} value='fa fa-youtube'>&#xf167; youtube</option>
<option {{  $selected == 'fa fa-youtube-play' ? 'selected' : '' }} value='fa fa-youtube-play'>&#xf16a; youtube-play</option>
<option {{  $selected == 'fa fa-youtube-square' ? 'selected' : '' }} value='fa fa-youtube-square'>&#xf166; youtube-square</option>
